// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pretty_block.proto

package db_inspect_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin                  []*TXInput  `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout                 []*TXOutput `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"`
	Tip                  string      `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetVin() []*TXInput {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVout() []*TXOutput {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *Transaction) GetTip() string {
	if m != nil {
		return m.Tip
	}
	return ""
}

type TXInput struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 int32    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey            string   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXInput) Reset()         { *m = TXInput{} }
func (m *TXInput) String() string { return proto.CompactTextString(m) }
func (*TXInput) ProtoMessage()    {}
func (*TXInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{1}
}

func (m *TXInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXInput.Unmarshal(m, b)
}
func (m *TXInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXInput.Marshal(b, m, deterministic)
}
func (m *TXInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXInput.Merge(m, src)
}
func (m *TXInput) XXX_Size() int {
	return xxx_messageInfo_TXInput.Size(m)
}
func (m *TXInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXInput.DiscardUnknown(m)
}

var xxx_messageInfo_TXInput proto.InternalMessageInfo

func (m *TXInput) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TXInput) GetVout() int32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TXInput) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *TXInput) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type TXOutput struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	PublicKeyHash        string   `protobuf:"bytes,2,opt,name=public_key_hash,json=publicKeyHash,proto3" json:"public_key_hash,omitempty"`
	Contract             string   `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXOutput) Reset()         { *m = TXOutput{} }
func (m *TXOutput) String() string { return proto.CompactTextString(m) }
func (*TXOutput) ProtoMessage()    {}
func (*TXOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{2}
}

func (m *TXOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXOutput.Unmarshal(m, b)
}
func (m *TXOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXOutput.Marshal(b, m, deterministic)
}
func (m *TXOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXOutput.Merge(m, src)
}
func (m *TXOutput) XXX_Size() int {
	return xxx_messageInfo_TXOutput.Size(m)
}
func (m *TXOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TXOutput proto.InternalMessageInfo

func (m *TXOutput) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TXOutput) GetPublicKeyHash() string {
	if m != nil {
		return m.PublicKeyHash
	}
	return ""
}

func (m *TXOutput) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PreviousHash         string   `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Height               uint64   `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{4}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BlockHeader) GetPreviousHash() string {
	if m != nil {
		return m.PreviousHash
	}
	return ""
}

func (m *BlockHeader) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Utxo struct {
	Amount               string   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PublicKeyHash        string   `protobuf:"bytes,2,opt,name=public_key_hash,json=publicKeyHash,proto3" json:"public_key_hash,omitempty"`
	Txid                 string   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	TxIndex              uint32   `protobuf:"varint,4,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Utxo) Reset()         { *m = Utxo{} }
func (m *Utxo) String() string { return proto.CompactTextString(m) }
func (*Utxo) ProtoMessage()    {}
func (*Utxo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d82741f9b246e68, []int{5}
}

func (m *Utxo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utxo.Unmarshal(m, b)
}
func (m *Utxo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utxo.Marshal(b, m, deterministic)
}
func (m *Utxo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utxo.Merge(m, src)
}
func (m *Utxo) XXX_Size() int {
	return xxx_messageInfo_Utxo.Size(m)
}
func (m *Utxo) XXX_DiscardUnknown() {
	xxx_messageInfo_Utxo.DiscardUnknown(m)
}

var xxx_messageInfo_Utxo proto.InternalMessageInfo

func (m *Utxo) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Utxo) GetPublicKeyHash() string {
	if m != nil {
		return m.PublicKeyHash
	}
	return ""
}

func (m *Utxo) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *Utxo) GetTxIndex() uint32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*Transaction)(nil), "db_inspect_pb.Transaction")
	proto.RegisterType((*TXInput)(nil), "db_inspect_pb.TXInput")
	proto.RegisterType((*TXOutput)(nil), "db_inspect_pb.TXOutput")
	proto.RegisterType((*Block)(nil), "db_inspect_pb.Block")
	proto.RegisterType((*BlockHeader)(nil), "db_inspect_pb.BlockHeader")
	proto.RegisterType((*Utxo)(nil), "db_inspect_pb.Utxo")
}

func init() { proto.RegisterFile("pretty_block.proto", fileDescriptor_4d82741f9b246e68) }

var fileDescriptor_4d82741f9b246e68 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xb1, 0x9d, 0x4d, 0x26, 0x9b, 0xb6, 0x88, 0x65, 0xeb, 0x2e, 0x2d, 0x04, 0x17, 0x8a,
	0xa1, 0x90, 0x43, 0x7a, 0xef, 0xa1, 0xa7, 0x5d, 0x7a, 0x28, 0x88, 0x2d, 0xf4, 0x66, 0x64, 0x5b,
	0xac, 0xc5, 0x26, 0x92, 0xb0, 0x46, 0xc1, 0xa1, 0xf7, 0xfe, 0x9e, 0xfe, 0xc4, 0x22, 0x59, 0xf9,
	0xec, 0x65, 0x6f, 0x7a, 0xe3, 0xa7, 0x37, 0x33, 0xef, 0xc9, 0x40, 0x74, 0xc7, 0x11, 0x77, 0x65,
	0xb5, 0x56, 0xf5, 0xf3, 0x52, 0x77, 0x0a, 0x15, 0x99, 0x37, 0x55, 0x29, 0xa4, 0xd1, 0xbc, 0xc6,
	0x52, 0x57, 0xf9, 0x9f, 0x08, 0x66, 0x8f, 0x1d, 0x93, 0x86, 0xd5, 0x28, 0x94, 0x24, 0xaf, 0x60,
	0x24, 0x9a, 0x2c, 0x5a, 0x44, 0xc5, 0x94, 0x8e, 0x44, 0x43, 0x0a, 0x88, 0xb7, 0x42, 0x66, 0xa3,
	0x45, 0x5c, 0xcc, 0x56, 0xb7, 0xcb, 0xb3, 0xcb, 0xcb, 0xc7, 0x5f, 0x0f, 0x52, 0x5b, 0xa4, 0x8e,
	0x42, 0x3e, 0x43, 0xb2, 0x55, 0x16, 0xb3, 0xd8, 0x53, 0xdf, 0xfe, 0x47, 0xfd, 0x61, 0xd1, 0x71,
	0x3d, 0x89, 0xbc, 0x81, 0x18, 0x85, 0xce, 0x12, 0xdf, 0xc7, 0x1d, 0x73, 0x09, 0x57, 0x41, 0x8e,
	0x10, 0x48, 0xb0, 0x3f, 0x4c, 0xe1, 0xcf, 0xae, 0xe6, 0xd5, 0x47, 0x8b, 0xa8, 0x48, 0x83, 0xc8,
	0x7b, 0x98, 0x1a, 0xf1, 0x24, 0x19, 0xda, 0x8e, 0x67, 0xb1, 0x27, 0x1f, 0x0b, 0xe4, 0x03, 0x80,
	0xb6, 0xd5, 0x5a, 0xd4, 0xe5, 0x33, 0xdf, 0x85, 0x4e, 0xd3, 0xa1, 0xf2, 0x9d, 0xef, 0xf2, 0x06,
	0x26, 0xfb, 0x99, 0xc8, 0x0d, 0xa4, 0x5b, 0xb6, 0xb6, 0x3c, 0x74, 0x1c, 0x00, 0xf9, 0x04, 0xaf,
	0x8f, 0x02, 0x65, 0xcb, 0x4c, 0xeb, 0xbb, 0x4f, 0xe9, 0xfc, 0xa0, 0x72, 0xcf, 0x4c, 0x4b, 0xee,
	0x60, 0x52, 0x2b, 0x89, 0x1d, 0xab, 0x31, 0x4c, 0x71, 0xc0, 0xf9, 0x6f, 0x48, 0xbf, 0x39, 0xf3,
	0xc9, 0x0a, 0xc6, 0x2d, 0x67, 0x0d, 0xef, 0x7c, 0x8f, 0xd9, 0xea, 0xee, 0xc2, 0x1f, 0xcf, 0xba,
	0xf7, 0x0c, 0x1a, 0x98, 0xe4, 0x2b, 0x5c, 0xe3, 0x31, 0x1a, 0x13, 0x42, 0xb8, 0xbc, 0x79, 0x92,
	0x1e, 0x3d, 0xe3, 0xe7, 0x7f, 0x23, 0x98, 0x9d, 0xe8, 0x3a, 0x0f, 0xfd, 0x16, 0xc1, 0x57, 0x77,
	0x26, 0x1f, 0x61, 0xae, 0x3b, 0xbe, 0x15, 0xca, 0x9a, 0xd3, 0x15, 0xaf, 0xf7, 0x45, 0xbf, 0xe1,
	0x0d, 0xa4, 0x52, 0xc9, 0x7a, 0x30, 0x39, 0xa6, 0x03, 0x70, 0xf6, 0xa3, 0xd8, 0x70, 0x83, 0x6c,
	0x33, 0x24, 0x19, 0xd3, 0x63, 0xe1, 0x3c, 0x9c, 0xf4, 0x32, 0x9c, 0x5b, 0x67, 0x87, 0x78, 0x6a,
	0x31, 0x1b, 0x2f, 0xa2, 0x22, 0xa1, 0x01, 0xe5, 0x16, 0x92, 0x9f, 0xd8, 0x2b, 0xf7, 0x9d, 0x6d,
	0x94, 0x95, 0x18, 0x86, 0x0d, 0xe8, 0xc5, 0x99, 0xec, 0x9f, 0x50, 0x7c, 0xf2, 0x84, 0xde, 0xc1,
	0x04, 0xfb, 0x52, 0xc8, 0x86, 0xf7, 0x7e, 0xdc, 0x39, 0xbd, 0xc2, 0xfe, 0xc1, 0xc1, 0x6a, 0xec,
	0xff, 0x8d, 0x2f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x13, 0x9b, 0xb7, 0x6d, 0x31, 0x03, 0x00,
	0x00,
}
