// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/client/pb/wallet_config.proto

package walletpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WalletConfig struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletConfig) Reset()         { *m = WalletConfig{} }
func (m *WalletConfig) String() string { return proto.CompactTextString(m) }
func (*WalletConfig) ProtoMessage()    {}
func (*WalletConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_wallet_config_45af80461c1164e2, []int{0}
}
func (m *WalletConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletConfig.Unmarshal(m, b)
}
func (m *WalletConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletConfig.Marshal(b, m, deterministic)
}
func (dst *WalletConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletConfig.Merge(dst, src)
}
func (m *WalletConfig) XXX_Size() int {
	return xxx_messageInfo_WalletConfig.Size(m)
}
func (m *WalletConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WalletConfig proto.InternalMessageInfo

func (m *WalletConfig) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*WalletConfig)(nil), "walletpb.WalletConfig")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/client/pb/wallet_config.proto", fileDescriptor_wallet_config_45af80461c1164e2)
}

var fileDescriptor_wallet_config_45af80461c1164e2 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x49, 0x2c, 0x28, 0xc8, 0x49, 0xad, 0xd4, 0x4f,
	0xcf, 0xd7, 0x85, 0x31, 0x93, 0x73, 0x32, 0x53, 0xf3, 0x4a, 0xf4, 0x0b, 0x92, 0xf4, 0xcb, 0x13,
	0x73, 0x72, 0x52, 0x4b, 0xe2, 0x93, 0xf3, 0xf3, 0xd2, 0x32, 0xd3, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0x20, 0x82, 0x05, 0x49, 0x4a, 0xda, 0x5c, 0x3c, 0xe1, 0x60, 0xb6, 0x33, 0x58,
	0x5e, 0x48, 0x9a, 0x8b, 0x33, 0x2d, 0x33, 0x27, 0x35, 0xbe, 0x20, 0xb1, 0x24, 0x43, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x33, 0x88, 0x03, 0x24, 0x10, 0x00, 0xe4, 0x27, 0xb1, 0x81, 0x75, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x82, 0x69, 0x05, 0x3e, 0x7c, 0x00, 0x00, 0x00,
}
