// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/core/pb/block.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	ParentHash           []byte         `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_62626fc7bede81d6, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Block) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	PreviousHash         []byte   `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	Nonce                int64    `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            []byte   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Height               uint64   `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Producer             string   `protobuf:"bytes,7,opt,name=producer,proto3" json:"producer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_62626fc7bede81d6, []int{1}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetPreviousHash() []byte {
	if m != nil {
		return m.PreviousHash
	}
	return nil
}

func (m *BlockHeader) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetProducer() string {
	if m != nil {
		return m.Producer
	}
	return ""
}

func init() {
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/core/pb/block.proto", fileDescriptor_block_62626fc7bede81d6)
}

var fileDescriptor_block_62626fc7bede81d6 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0xc9, 0x7e, 0x54, 0x77, 0xb6, 0x5e, 0xa2, 0x48, 0x58, 0x04, 0xcb, 0x7a, 0x29, 0x88,
	0x2d, 0xea, 0x61, 0xef, 0x9e, 0xf6, 0x1c, 0xbc, 0x4b, 0x9a, 0x86, 0x26, 0xb8, 0x4d, 0x42, 0x92,
	0x0a, 0xbe, 0x84, 0x4f, 0xe6, 0x43, 0x49, 0xd3, 0x5d, 0x5b, 0x6f, 0xde, 0xe6, 0xff, 0x31, 0xbf,
	0x81, 0x81, 0xc7, 0x46, 0x05, 0xd9, 0x55, 0x05, 0x37, 0x6d, 0x59, 0x33, 0x6b, 0x0f, 0xe2, 0xb3,
	0x6c, 0xcc, 0xc3, 0x69, 0xe4, 0xc6, 0x89, 0xd2, 0x56, 0x65, 0x75, 0x30, 0xfc, 0xbd, 0xb0, 0xce,
	0x04, 0x83, 0x93, 0xde, 0xb4, 0xd5, 0x66, 0xf7, 0xbf, 0xd5, 0xe0, 0x98, 0xf6, 0x8c, 0x07, 0x65,
	0xf4, 0x00, 0xd8, 0x7e, 0x21, 0x58, 0xbe, 0xf4, 0x40, 0x7c, 0x0f, 0x89, 0x14, 0xac, 0x16, 0x8e,
	0xa0, 0x0c, 0xe5, 0xeb, 0xa7, 0xcb, 0x62, 0x60, 0x17, 0x31, 0xde, 0xc7, 0x88, 0x1e, 0x2b, 0x78,
	0x07, 0xe9, 0x84, 0xe5, 0xc9, 0x2c, 0x9b, 0x4f, 0x57, 0x5e, 0xc7, 0x8c, 0xfe, 0x29, 0xe2, 0x5b,
	0x58, 0x5b, 0xe6, 0x84, 0x0e, 0x6f, 0x92, 0x79, 0x49, 0xe6, 0x19, 0xca, 0x53, 0x0a, 0x83, 0xb5,
	0x67, 0x5e, 0x6e, 0xbf, 0x11, 0xac, 0x27, 0x17, 0x31, 0x86, 0x45, 0x6c, 0xa2, 0xd8, 0x8c, 0x33,
	0xbe, 0x83, 0x0b, 0xeb, 0xc4, 0x87, 0x32, 0x9d, 0x1f, 0x30, 0xb3, 0x18, 0xa6, 0x27, 0xb3, 0x07,
	0xe1, 0x2b, 0x58, 0x6a, 0xa3, 0xb9, 0x88, 0x37, 0xe6, 0x74, 0x10, 0xf8, 0x06, 0x56, 0x41, 0xb5,
	0xc2, 0x07, 0xd6, 0x5a, 0xb2, 0x88, 0xc9, 0x68, 0xf4, 0xa9, 0x57, 0x8d, 0x66, 0xa1, 0x73, 0x82,
	0x2c, 0x23, 0x74, 0x34, 0xf0, 0x75, 0xff, 0x21, 0xd5, 0xc8, 0x40, 0x92, 0x0c, 0xe5, 0x0b, 0x7a,
	0x54, 0x78, 0x03, 0xe7, 0xd6, 0x99, 0xba, 0xe3, 0xc2, 0x91, 0xb3, 0x0c, 0xe5, 0x2b, 0xfa, 0xab,
	0xab, 0x24, 0xbe, 0xf9, 0xf9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x92, 0x93, 0xe7, 0x29, 0xdc, 0x01,
	0x00, 0x00,
}
