// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core/pb/changelog.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Log                  map[string]string `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b4bc50834eedb3, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetLog() map[string]string {
	if m != nil {
		return m.Log
	}
	return nil
}

type ChangeLog struct {
	Log                  map[string]*Log `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChangeLog) Reset()         { *m = ChangeLog{} }
func (m *ChangeLog) String() string { return proto.CompactTextString(m) }
func (*ChangeLog) ProtoMessage()    {}
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b4bc50834eedb3, []int{1}
}

func (m *ChangeLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeLog.Unmarshal(m, b)
}
func (m *ChangeLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeLog.Marshal(b, m, deterministic)
}
func (m *ChangeLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeLog.Merge(m, src)
}
func (m *ChangeLog) XXX_Size() int {
	return xxx_messageInfo_ChangeLog.Size(m)
}
func (m *ChangeLog) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeLog.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeLog proto.InternalMessageInfo

func (m *ChangeLog) GetLog() map[string]*Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "corepb.Log")
	proto.RegisterMapType((map[string]string)(nil), "corepb.Log.LogEntry")
	proto.RegisterType((*ChangeLog)(nil), "corepb.ChangeLog")
	proto.RegisterMapType((map[string]*Log)(nil), "corepb.ChangeLog.LogEntry")
}

func init() { proto.RegisterFile("core/pb/changelog.proto", fileDescriptor_b9b4bc50834eedb3) }

var fileDescriptor_b9b4bc50834eedb3 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0x2f, 0x4a,
	0xd5, 0x2f, 0x48, 0xd2, 0x4f, 0xce, 0x48, 0xcc, 0x4b, 0x4f, 0xcd, 0xc9, 0x4f, 0xd7, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x49, 0x14, 0x24, 0x29, 0xa5, 0x72, 0x31, 0xfb, 0xe4, 0xa7,
	0x0b, 0xa9, 0x71, 0x31, 0xe7, 0xe4, 0xa7, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xe8,
	0x41, 0x24, 0xf5, 0x7c, 0xf2, 0xd3, 0x41, 0xd8, 0x35, 0xaf, 0xa4, 0xa8, 0x32, 0x08, 0xa4, 0x40,
	0xca, 0x8c, 0x8b, 0x03, 0x26, 0x20, 0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30,
	0x81, 0xc5, 0x20, 0x1c, 0x2b, 0x26, 0x0b, 0x46, 0xa5, 0x3a, 0x2e, 0x4e, 0x67, 0xb0, 0x0b, 0x40,
	0x96, 0xe9, 0x20, 0x5b, 0x26, 0x05, 0xb3, 0x0c, 0x2e, 0x8f, 0x66, 0xa5, 0x33, 0x5e, 0x2b, 0x15,
	0x91, 0xad, 0xe4, 0x36, 0xe2, 0x46, 0x72, 0x3a, 0x92, 0xfd, 0x49, 0x6c, 0x60, 0x5f, 0x1b, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x28, 0x92, 0xb6, 0x29, 0x10, 0x01, 0x00, 0x00,
}
