// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transaction struct {
	ID                   []byte      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Vin                  []*TXInput  `protobuf:"bytes,2,rep,name=Vin,proto3" json:"Vin,omitempty"`
	Vout                 []*TXOutput `protobuf:"bytes,3,rep,name=Vout,proto3" json:"Vout,omitempty"`
	Tip                  uint64      `protobuf:"varint,4,opt,name=Tip,proto3" json:"Tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b8f31b70f4339c1, []int{0}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Transaction) GetVin() []*TXInput {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVout() []*TXOutput {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *Transaction) GetTip() uint64 {
	if m != nil {
		return m.Tip
	}
	return 0
}

type TXInput struct {
	Txid                 []byte   `protobuf:"bytes,1,opt,name=Txid,proto3" json:"Txid,omitempty"`
	Vout                 int32    `protobuf:"varint,2,opt,name=Vout,proto3" json:"Vout,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	PubKey               []byte   `protobuf:"bytes,4,opt,name=PubKey,proto3" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXInput) Reset()         { *m = TXInput{} }
func (m *TXInput) String() string { return proto.CompactTextString(m) }
func (*TXInput) ProtoMessage()    {}
func (*TXInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b8f31b70f4339c1, []int{1}
}
func (m *TXInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXInput.Unmarshal(m, b)
}
func (m *TXInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXInput.Marshal(b, m, deterministic)
}
func (dst *TXInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXInput.Merge(dst, src)
}
func (m *TXInput) XXX_Size() int {
	return xxx_messageInfo_TXInput.Size(m)
}
func (m *TXInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXInput.DiscardUnknown(m)
}

var xxx_messageInfo_TXInput proto.InternalMessageInfo

func (m *TXInput) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *TXInput) GetVout() int32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TXInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TXInput) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type TXOutput struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	PubKeyHash           []byte   `protobuf:"bytes,2,opt,name=PubKeyHash,proto3" json:"PubKeyHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXOutput) Reset()         { *m = TXOutput{} }
func (m *TXOutput) String() string { return proto.CompactTextString(m) }
func (*TXOutput) ProtoMessage()    {}
func (*TXOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_1b8f31b70f4339c1, []int{2}
}
func (m *TXOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXOutput.Unmarshal(m, b)
}
func (m *TXOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXOutput.Marshal(b, m, deterministic)
}
func (dst *TXOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXOutput.Merge(dst, src)
}
func (m *TXOutput) XXX_Size() int {
	return xxx_messageInfo_TXOutput.Size(m)
}
func (m *TXOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TXOutput proto.InternalMessageInfo

func (m *TXOutput) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TXOutput) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*TXInput)(nil), "corepb.TXInput")
	proto.RegisterType((*TXOutput)(nil), "corepb.TXOutput")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_transaction_1b8f31b70f4339c1) }

var fileDescriptor_transaction_1b8f31b70f4339c1 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0xd3, 0x56, 0x9d, 0x2d, 0xba, 0x0e, 0x22, 0x39, 0x88, 0xd4, 0xe2, 0xa1, 0xa7,
	0x1e, 0xf4, 0x0f, 0x78, 0xd8, 0x83, 0xc5, 0x83, 0x12, 0x4b, 0xf1, 0x9a, 0xae, 0x65, 0x0d, 0x48,
	0x52, 0xba, 0x09, 0xd4, 0x7f, 0x2f, 0x99, 0x46, 0xea, 0x6d, 0xe6, 0xbd, 0x2f, 0xef, 0x85, 0x81,
	0x4b, 0x3b, 0x49, 0x7d, 0x94, 0x7b, 0xab, 0x8c, 0xae, 0xc7, 0xc9, 0x58, 0x83, 0xd9, 0xde, 0x4c,
	0xc3, 0xd8, 0x97, 0x33, 0x6c, 0xda, 0xd5, 0xc4, 0x73, 0x88, 0x9b, 0x1d, 0x8f, 0x8a, 0xa8, 0xca,
	0x45, 0xdc, 0xec, 0xf0, 0x0e, 0x58, 0xa7, 0x34, 0x8f, 0x0b, 0x56, 0x6d, 0x1e, 0x2e, 0xea, 0xe5,
	0x51, 0xdd, 0x7e, 0x34, 0x7a, 0x74, 0x56, 0x78, 0x0f, 0xef, 0x21, 0xe9, 0x8c, 0xb3, 0x9c, 0x11,
	0xb3, 0x5d, 0x99, 0x57, 0x67, 0x3d, 0x44, 0x2e, 0x6e, 0x81, 0xb5, 0x6a, 0xe4, 0x49, 0x11, 0x55,
	0x89, 0xf0, 0x63, 0x79, 0x80, 0x93, 0x90, 0x83, 0x08, 0x49, 0x3b, 0xab, 0xcf, 0xd0, 0x4b, 0xb3,
	0xd7, 0x28, 0x36, 0x2e, 0xa2, 0x2a, 0x0d, 0x21, 0x37, 0x70, 0xf6, 0xae, 0x0e, 0x5a, 0x5a, 0x37,
	0x0d, 0x9c, 0x11, 0xbc, 0x0a, 0x78, 0x0d, 0xd9, 0x9b, 0xeb, 0x5f, 0x86, 0x1f, 0x6a, 0xc9, 0x45,
	0xd8, 0xca, 0x27, 0x38, 0xfd, 0xfb, 0x0c, 0x5e, 0x41, 0xda, 0xc9, 0x6f, 0x37, 0x50, 0x55, 0x2a,
	0x96, 0x05, 0x6f, 0x01, 0x16, 0xf6, 0x59, 0x1e, 0xbf, 0xa8, 0x31, 0x17, 0xff, 0x94, 0x3e, 0xa3,
	0x9b, 0x3d, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xb4, 0x57, 0x3d, 0x48, 0x01, 0x00, 0x00,
}
