// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/core/pb/transaction.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_6b368b9d8c3b42bc, []int{0}
}
func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (dst *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(dst, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Transaction struct {
	Id                   []byte      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vin                  []*TXInput  `protobuf:"bytes,2,rep,name=vin,proto3" json:"vin,omitempty"`
	Vout                 []*TXOutput `protobuf:"bytes,3,rep,name=vout,proto3" json:"vout,omitempty"`
	Tip                  []byte      `protobuf:"bytes,4,opt,name=tip,proto3" json:"tip,omitempty"`
	GasLimit             []byte      `protobuf:"bytes,5,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice             []byte      `protobuf:"bytes,6,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_6b368b9d8c3b42bc, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Transaction) GetVin() []*TXInput {
	if m != nil {
		return m.Vin
	}
	return nil
}

func (m *Transaction) GetVout() []*TXOutput {
	if m != nil {
		return m.Vout
	}
	return nil
}

func (m *Transaction) GetTip() []byte {
	if m != nil {
		return m.Tip
	}
	return nil
}

func (m *Transaction) GetGasLimit() []byte {
	if m != nil {
		return m.GasLimit
	}
	return nil
}

func (m *Transaction) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

type TXInput struct {
	Txid                 []byte   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Vout                 int32    `protobuf:"varint,2,opt,name=vout,proto3" json:"vout,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXInput) Reset()         { *m = TXInput{} }
func (m *TXInput) String() string { return proto.CompactTextString(m) }
func (*TXInput) ProtoMessage()    {}
func (*TXInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_6b368b9d8c3b42bc, []int{2}
}
func (m *TXInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXInput.Unmarshal(m, b)
}
func (m *TXInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXInput.Marshal(b, m, deterministic)
}
func (dst *TXInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXInput.Merge(dst, src)
}
func (m *TXInput) XXX_Size() int {
	return xxx_messageInfo_TXInput.Size(m)
}
func (m *TXInput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXInput.DiscardUnknown(m)
}

var xxx_messageInfo_TXInput proto.InternalMessageInfo

func (m *TXInput) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *TXInput) GetVout() int32 {
	if m != nil {
		return m.Vout
	}
	return 0
}

func (m *TXInput) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *TXInput) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type TXOutput struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	PublicKeyHash        []byte   `protobuf:"bytes,2,opt,name=public_key_hash,json=publicKeyHash,proto3" json:"public_key_hash,omitempty"`
	Contract             string   `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TXOutput) Reset()         { *m = TXOutput{} }
func (m *TXOutput) String() string { return proto.CompactTextString(m) }
func (*TXOutput) ProtoMessage()    {}
func (*TXOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_transaction_6b368b9d8c3b42bc, []int{3}
}
func (m *TXOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TXOutput.Unmarshal(m, b)
}
func (m *TXOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TXOutput.Marshal(b, m, deterministic)
}
func (dst *TXOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TXOutput.Merge(dst, src)
}
func (m *TXOutput) XXX_Size() int {
	return xxx_messageInfo_TXOutput.Size(m)
}
func (m *TXOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_TXOutput.DiscardUnknown(m)
}

var xxx_messageInfo_TXOutput proto.InternalMessageInfo

func (m *TXOutput) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *TXOutput) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *TXOutput) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func init() {
	proto.RegisterType((*Transactions)(nil), "corepb.Transactions")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*TXInput)(nil), "corepb.TXInput")
	proto.RegisterType((*TXOutput)(nil), "corepb.TXOutput")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/core/pb/transaction.proto", fileDescriptor_transaction_6b368b9d8c3b42bc)
}

var fileDescriptor_transaction_6b368b9d8c3b42bc = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x41, 0x4f, 0xe3, 0x30,
	0x10, 0x85, 0x95, 0xa4, 0xed, 0x36, 0xd3, 0xec, 0xb6, 0xf2, 0xee, 0xc1, 0x5a, 0x40, 0x2a, 0x11,
	0x42, 0xbd, 0x90, 0x48, 0x70, 0xe8, 0x4f, 0x00, 0x04, 0x12, 0x28, 0xe2, 0xc0, 0xad, 0x72, 0x12,
	0x2b, 0xb1, 0x48, 0x6d, 0x2b, 0xb6, 0x2b, 0xfa, 0xb7, 0xf8, 0x85, 0xc8, 0x6e, 0x9a, 0x94, 0xdb,
	0xcc, 0x7b, 0x9f, 0xde, 0x3c, 0xcb, 0xb0, 0xae, 0x98, 0xae, 0x4d, 0x9e, 0x14, 0x62, 0x9b, 0x96,
	0x44, 0xca, 0x86, 0xee, 0xd3, 0x4a, 0xdc, 0x1c, 0xc7, 0x42, 0xb4, 0x34, 0x95, 0x79, 0xaa, 0x5b,
	0xc2, 0x15, 0x29, 0x34, 0x13, 0x3c, 0x91, 0xad, 0xd0, 0x02, 0x4d, 0xac, 0x25, 0xf3, 0xf8, 0x1e,
	0xa2, 0xb7, 0xc1, 0x54, 0x68, 0x0d, 0xd1, 0x09, 0xac, 0xb0, 0xb7, 0x0c, 0x56, 0xb3, 0xdb, 0xbf,
	0xc9, 0x01, 0x4f, 0x4e, 0xd8, 0xec, 0x07, 0x18, 0x7f, 0x79, 0x30, 0x3b, 0x71, 0xd1, 0x1f, 0xf0,
	0x59, 0x89, 0xbd, 0xa5, 0xb7, 0x8a, 0x32, 0x9f, 0x95, 0xe8, 0x12, 0x82, 0x1d, 0xe3, 0xd8, 0x77,
	0x79, 0xf3, 0x3e, 0xef, 0xfd, 0x91, 0x4b, 0xa3, 0x33, 0xeb, 0xa1, 0x2b, 0x18, 0xed, 0x84, 0xd1,
	0x38, 0x70, 0xcc, 0x62, 0x60, 0x5e, 0x8c, 0xb6, 0x90, 0x73, 0xd1, 0x02, 0x02, 0xcd, 0x24, 0x1e,
	0xb9, 0x64, 0x3b, 0xa2, 0x33, 0x08, 0x2b, 0xa2, 0x36, 0x0d, 0xdb, 0x32, 0x8d, 0xc7, 0x4e, 0x9f,
	0x56, 0x44, 0x3d, 0xdb, 0xfd, 0x68, 0xca, 0x96, 0x15, 0x14, 0x4f, 0x7a, 0xf3, 0xd5, 0xee, 0x31,
	0x87, 0x5f, 0x5d, 0x03, 0x84, 0x60, 0xa4, 0x3f, 0xfb, 0xc6, 0x6e, 0xb6, 0x9a, 0x2b, 0xe4, 0x2f,
	0xbd, 0xd5, 0xb8, 0x3b, 0x7f, 0x0e, 0xa1, 0x62, 0x15, 0x27, 0xda, 0xb4, 0x14, 0x07, 0x0e, 0x1e,
	0x04, 0x74, 0x01, 0x20, 0x4d, 0xde, 0xb0, 0x62, 0xf3, 0x41, 0xf7, 0x5d, 0xc7, 0xf0, 0xa0, 0x3c,
	0xd1, 0x7d, 0x5c, 0xc2, 0xf4, 0xf8, 0x1a, 0xf4, 0x0f, 0xc6, 0x3b, 0xd2, 0x18, 0xda, 0x5d, 0x3c,
	0x2c, 0xe8, 0x1a, 0xe6, 0x43, 0xc0, 0xa6, 0x26, 0xaa, 0x76, 0xd7, 0xa3, 0xec, 0x77, 0x9f, 0xf2,
	0x40, 0x54, 0x8d, 0xfe, 0xc3, 0xb4, 0x10, 0x5c, 0xb7, 0xa4, 0xd0, 0xae, 0x45, 0x98, 0xf5, 0x7b,
	0x3e, 0x71, 0x5f, 0x7c, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x64, 0x32, 0x58, 0x1d, 0x02,
	0x00, 0x00,
}
