// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/core/pb/transactionPool.proto

package corepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionNode struct {
	Children             map[string]*Transaction `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                *Transaction            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TransactionNode) Reset()         { *m = TransactionNode{} }
func (m *TransactionNode) String() string { return proto.CompactTextString(m) }
func (*TransactionNode) ProtoMessage()    {}
func (*TransactionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionPool_1cfd409565c41ff3, []int{0}
}
func (m *TransactionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionNode.Unmarshal(m, b)
}
func (m *TransactionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionNode.Marshal(b, m, deterministic)
}
func (dst *TransactionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionNode.Merge(dst, src)
}
func (m *TransactionNode) XXX_Size() int {
	return xxx_messageInfo_TransactionNode.Size(m)
}
func (m *TransactionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionNode.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionNode proto.InternalMessageInfo

func (m *TransactionNode) GetChildren() map[string]*Transaction {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *TransactionNode) GetValue() *Transaction {
	if m != nil {
		return m.Value
	}
	return nil
}

type TransactionPool struct {
	Txs                  map[string]*TransactionNode `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TipOrder             []string                    `protobuf:"bytes,2,rep,name=tipOrder,proto3" json:"tipOrder,omitempty"`
	Limit                uint32                      `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TransactionPool) Reset()         { *m = TransactionPool{} }
func (m *TransactionPool) String() string { return proto.CompactTextString(m) }
func (*TransactionPool) ProtoMessage()    {}
func (*TransactionPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_transactionPool_1cfd409565c41ff3, []int{1}
}
func (m *TransactionPool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionPool.Unmarshal(m, b)
}
func (m *TransactionPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionPool.Marshal(b, m, deterministic)
}
func (dst *TransactionPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionPool.Merge(dst, src)
}
func (m *TransactionPool) XXX_Size() int {
	return xxx_messageInfo_TransactionPool.Size(m)
}
func (m *TransactionPool) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionPool.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionPool proto.InternalMessageInfo

func (m *TransactionPool) GetTxs() map[string]*TransactionNode {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *TransactionPool) GetTipOrder() []string {
	if m != nil {
		return m.TipOrder
	}
	return nil
}

func (m *TransactionPool) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func init() {
	proto.RegisterType((*TransactionNode)(nil), "corepb.TransactionNode")
	proto.RegisterMapType((map[string]*Transaction)(nil), "corepb.TransactionNode.ChildrenEntry")
	proto.RegisterType((*TransactionPool)(nil), "corepb.TransactionPool")
	proto.RegisterMapType((map[string]*TransactionNode)(nil), "corepb.TransactionPool.TxsEntry")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/core/pb/transactionPool.proto", fileDescriptor_transactionPool_1cfd409565c41ff3)
}

var fileDescriptor_transactionPool_1cfd409565c41ff3 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x49, 0x2c, 0x28, 0xc8, 0x49, 0xad, 0xd4, 0x4f,
	0xcf, 0xd7, 0x85, 0x31, 0x93, 0xf3, 0x8b, 0x52, 0xf5, 0x0b, 0x92, 0xf4, 0x4b, 0x8a, 0x12, 0xf3,
	0x8a, 0x13, 0x93, 0x4b, 0x32, 0xf3, 0xf3, 0x02, 0xf2, 0xf3, 0x73, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0xd8, 0x40, 0xd2, 0x05, 0x49, 0x52, 0xe6, 0x24, 0x1b, 0x02, 0x31, 0x40, 0xe9, 0x22,
	0x23, 0x17, 0x7f, 0x08, 0x42, 0xd4, 0x2f, 0x3f, 0x25, 0x55, 0xc8, 0x91, 0x8b, 0x23, 0x39, 0x23,
	0x33, 0x27, 0xa5, 0x28, 0x35, 0x4f, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x55, 0x0f, 0x62,
	0x8f, 0x1e, 0x9a, 0x52, 0x3d, 0x67, 0xa8, 0x3a, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0xb8, 0x36,
	0x21, 0x4d, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23,
	0x61, 0x2c, 0xfa, 0x83, 0x20, 0x2a, 0xa4, 0x02, 0xb8, 0x78, 0x51, 0x4c, 0x11, 0x12, 0xe0, 0x62,
	0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x49, 0x30, 0xcd, 0x8a,
	0xc9, 0x82, 0x51, 0xe9, 0x04, 0xaa, 0x9f, 0x40, 0xc1, 0x25, 0x64, 0xc4, 0xc5, 0x5c, 0x52, 0x51,
	0x0c, 0xf5, 0x8e, 0x02, 0x16, 0x03, 0xc0, 0x81, 0x1a, 0x52, 0x51, 0x0c, 0xf1, 0x09, 0x48, 0xb1,
	0x90, 0x14, 0x17, 0x47, 0x49, 0x66, 0x81, 0x7f, 0x51, 0x4a, 0x6a, 0x91, 0x04, 0x93, 0x02, 0xb3,
	0x06, 0x67, 0x10, 0x9c, 0x2f, 0x24, 0xc2, 0xc5, 0x9a, 0x93, 0x99, 0x9b, 0x59, 0x22, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x1b, 0x04, 0xe1, 0x48, 0xf9, 0x73, 0x71, 0xc0, 0x8c, 0xc0, 0xe2, 0x0d, 0x5d,
	0x54, 0x6f, 0x88, 0xe3, 0x08, 0x54, 0x24, 0xaf, 0x24, 0xb1, 0x81, 0x63, 0xc9, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x18, 0x99, 0x6d, 0x25, 0x02, 0x00, 0x00,
}
