// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/core/account/pb/account.proto

package accountpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	KeyPair              *KeyPair `protobuf:"bytes,1,opt,name=keyPair,proto3" json:"keyPair,omitempty"`
	Address              *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PubKeyHash           []byte   `protobuf:"bytes,3,opt,name=pubKeyHash,proto3" json:"pubKeyHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2a7a0985c59efe, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetKeyPair() *KeyPair {
	if m != nil {
		return m.KeyPair
	}
	return nil
}

func (m *Account) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Account) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

type ContractAccount struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PubKeyHash           []byte   `protobuf:"bytes,2,opt,name=pubKeyHash,proto3" json:"pubKeyHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractAccount) Reset()         { *m = ContractAccount{} }
func (m *ContractAccount) String() string { return proto.CompactTextString(m) }
func (*ContractAccount) ProtoMessage()    {}
func (*ContractAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2a7a0985c59efe, []int{1}
}

func (m *ContractAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractAccount.Unmarshal(m, b)
}
func (m *ContractAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractAccount.Marshal(b, m, deterministic)
}
func (m *ContractAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractAccount.Merge(m, src)
}
func (m *ContractAccount) XXX_Size() int {
	return xxx_messageInfo_ContractAccount.Size(m)
}
func (m *ContractAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ContractAccount proto.InternalMessageInfo

func (m *ContractAccount) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *ContractAccount) GetPubKeyHash() []byte {
	if m != nil {
		return m.PubKeyHash
	}
	return nil
}

type KeyPair struct {
	PrivateKey           []byte   `protobuf:"bytes,1,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyPair) Reset()         { *m = KeyPair{} }
func (m *KeyPair) String() string { return proto.CompactTextString(m) }
func (*KeyPair) ProtoMessage()    {}
func (*KeyPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2a7a0985c59efe, []int{2}
}

func (m *KeyPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyPair.Unmarshal(m, b)
}
func (m *KeyPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyPair.Marshal(b, m, deterministic)
}
func (m *KeyPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyPair.Merge(m, src)
}
func (m *KeyPair) XXX_Size() int {
	return xxx_messageInfo_KeyPair.Size(m)
}
func (m *KeyPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyPair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyPair proto.InternalMessageInfo

func (m *KeyPair) GetPrivateKey() []byte {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *KeyPair) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2a7a0985c59efe, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AccountConfig struct {
	FilePath             string   `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountConfig) Reset()         { *m = AccountConfig{} }
func (m *AccountConfig) String() string { return proto.CompactTextString(m) }
func (*AccountConfig) ProtoMessage()    {}
func (*AccountConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea2a7a0985c59efe, []int{4}
}

func (m *AccountConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountConfig.Unmarshal(m, b)
}
func (m *AccountConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountConfig.Marshal(b, m, deterministic)
}
func (m *AccountConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountConfig.Merge(m, src)
}
func (m *AccountConfig) XXX_Size() int {
	return xxx_messageInfo_AccountConfig.Size(m)
}
func (m *AccountConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AccountConfig proto.InternalMessageInfo

func (m *AccountConfig) GetFilePath() string {
	if m != nil {
		return m.FilePath
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "accountpb.Account")
	proto.RegisterType((*ContractAccount)(nil), "accountpb.ContractAccount")
	proto.RegisterType((*KeyPair)(nil), "accountpb.KeyPair")
	proto.RegisterType((*Address)(nil), "accountpb.Address")
	proto.RegisterType((*AccountConfig)(nil), "accountpb.AccountConfig")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/core/account/pb/account.proto", fileDescriptor_ea2a7a0985c59efe)
}

var fileDescriptor_ea2a7a0985c59efe = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xc9, 0x0a, 0xd6, 0x8e, 0x8a, 0x90, 0x53, 0x41, 0x91, 0xa5, 0x5e, 0xf6, 0xb0, 0xb6,
	0xa0, 0x47, 0x4f, 0xcb, 0x1e, 0x14, 0x7a, 0x59, 0xfa, 0x07, 0x96, 0x49, 0x9a, 0x6d, 0x83, 0xb5,
	0x09, 0x69, 0x2a, 0xf4, 0x07, 0xf8, 0xbf, 0xa5, 0x6d, 0x52, 0x57, 0xf6, 0xb4, 0xb7, 0xcc, 0x7b,
	0x1f, 0xf3, 0xde, 0x10, 0x78, 0x2b, 0xa5, 0xad, 0x3a, 0x96, 0x70, 0xf5, 0x95, 0x16, 0xa8, 0x75,
	0x2d, 0xfa, 0xb4, 0x54, 0xcf, 0xfe, 0xc9, 0x95, 0x11, 0x29, 0x72, 0xae, 0xba, 0xc6, 0xa6, 0x9a,
	0xf9, 0x67, 0xa2, 0x8d, 0xb2, 0x8a, 0x86, 0x6e, 0xd4, 0x2c, 0xfe, 0x21, 0x10, 0x6c, 0xa6, 0x89,
	0xae, 0x21, 0xf8, 0x14, 0xfd, 0x0e, 0xa5, 0x89, 0xc8, 0x92, 0xac, 0xae, 0x5f, 0x68, 0x32, 0x83,
	0x49, 0x36, 0x39, 0xb9, 0x47, 0x06, 0x1a, 0x8b, 0xc2, 0x88, 0xb6, 0x8d, 0x16, 0x27, 0xf4, 0x66,
	0x72, 0x72, 0x8f, 0xd0, 0x47, 0x00, 0xdd, 0xb1, 0x4c, 0xf4, 0x1f, 0xd8, 0x56, 0xd1, 0xc5, 0x92,
	0xac, 0x6e, 0xf2, 0x23, 0x25, 0xde, 0xc3, 0xdd, 0x56, 0x35, 0xd6, 0x20, 0xb7, 0x47, 0x75, 0x7c,
	0x00, 0x39, 0x37, 0x60, 0x71, 0x12, 0xf0, 0x0e, 0x81, 0x3b, 0x61, 0x44, 0x8d, 0xfc, 0x46, 0x2b,
	0x32, 0xd1, 0x8f, 0xbb, 0x07, 0x74, 0x56, 0xe8, 0x03, 0x84, 0xba, 0x63, 0xb5, 0xe4, 0x83, 0x3d,
	0x6d, 0xfa, 0x13, 0xe2, 0x27, 0x08, 0x5c, 0x38, 0x8d, 0xfe, 0x37, 0x0c, 0xe7, 0x36, 0xf1, 0x1a,
	0x6e, 0xdd, 0x19, 0x5b, 0xd5, 0x1c, 0x64, 0x49, 0xef, 0x21, 0x3c, 0xc8, 0x5a, 0xec, 0x35, 0xda,
	0xca, 0xc1, 0x57, 0x83, 0xb0, 0x43, 0x5b, 0xb1, 0xcb, 0xf1, 0x5b, 0x5e, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x08, 0xa0, 0xb0, 0x5b, 0xd5, 0x01, 0x00, 0x00,
}
