// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/network/pb/dapmsg.proto

package networkpb

import (
	fmt "fmt"
	pb "github.com/dappley/go-dappley/core/pb"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dapmsg struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	UnixTimeRecvd        int64    `protobuf:"varint,3,opt,name=unixTimeRecvd,proto3" json:"unixTimeRecvd,omitempty"`
	Key                  string   `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	UniOrBroadcast       int64    `protobuf:"varint,5,opt,name=uniOrBroadcast,proto3" json:"uniOrBroadcast,omitempty"`
	Counter              uint64   `protobuf:"varint,6,opt,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dapmsg) Reset()         { *m = Dapmsg{} }
func (m *Dapmsg) String() string { return proto.CompactTextString(m) }
func (*Dapmsg) ProtoMessage()    {}
func (*Dapmsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_823c192163b402a3, []int{0}
}

func (m *Dapmsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dapmsg.Unmarshal(m, b)
}
func (m *Dapmsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dapmsg.Marshal(b, m, deterministic)
}
func (m *Dapmsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dapmsg.Merge(m, src)
}
func (m *Dapmsg) XXX_Size() int {
	return xxx_messageInfo_Dapmsg.Size(m)
}
func (m *Dapmsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Dapmsg.DiscardUnknown(m)
}

var xxx_messageInfo_Dapmsg proto.InternalMessageInfo

func (m *Dapmsg) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *Dapmsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Dapmsg) GetUnixTimeRecvd() int64 {
	if m != nil {
		return m.UnixTimeRecvd
	}
	return 0
}

func (m *Dapmsg) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Dapmsg) GetUniOrBroadcast() int64 {
	if m != nil {
		return m.UniOrBroadcast
	}
	return 0
}

func (m *Dapmsg) GetCounter() uint64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type GetBlockchainInfo struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainInfo) Reset()         { *m = GetBlockchainInfo{} }
func (m *GetBlockchainInfo) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainInfo) ProtoMessage()    {}
func (*GetBlockchainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_823c192163b402a3, []int{1}
}

func (m *GetBlockchainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainInfo.Unmarshal(m, b)
}
func (m *GetBlockchainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainInfo.Marshal(b, m, deterministic)
}
func (m *GetBlockchainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainInfo.Merge(m, src)
}
func (m *GetBlockchainInfo) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainInfo.Size(m)
}
func (m *GetBlockchainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainInfo proto.InternalMessageInfo

func (m *GetBlockchainInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ReturnBlockchainInfo struct {
	TailBlockHash        []byte   `protobuf:"bytes,1,opt,name=tailBlockHash,proto3" json:"tailBlockHash,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,2,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBlockchainInfo) Reset()         { *m = ReturnBlockchainInfo{} }
func (m *ReturnBlockchainInfo) String() string { return proto.CompactTextString(m) }
func (*ReturnBlockchainInfo) ProtoMessage()    {}
func (*ReturnBlockchainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_823c192163b402a3, []int{2}
}

func (m *ReturnBlockchainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBlockchainInfo.Unmarshal(m, b)
}
func (m *ReturnBlockchainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBlockchainInfo.Marshal(b, m, deterministic)
}
func (m *ReturnBlockchainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBlockchainInfo.Merge(m, src)
}
func (m *ReturnBlockchainInfo) XXX_Size() int {
	return xxx_messageInfo_ReturnBlockchainInfo.Size(m)
}
func (m *ReturnBlockchainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBlockchainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBlockchainInfo proto.InternalMessageInfo

func (m *ReturnBlockchainInfo) GetTailBlockHash() []byte {
	if m != nil {
		return m.TailBlockHash
	}
	return nil
}

func (m *ReturnBlockchainInfo) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ReturnBlockchainInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type GetBlocks struct {
	StartBlockHashes     [][]byte `protobuf:"bytes,1,rep,name=startBlockHashes,proto3" json:"startBlockHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlocks) Reset()         { *m = GetBlocks{} }
func (m *GetBlocks) String() string { return proto.CompactTextString(m) }
func (*GetBlocks) ProtoMessage()    {}
func (*GetBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_823c192163b402a3, []int{3}
}

func (m *GetBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlocks.Unmarshal(m, b)
}
func (m *GetBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlocks.Marshal(b, m, deterministic)
}
func (m *GetBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlocks.Merge(m, src)
}
func (m *GetBlocks) XXX_Size() int {
	return xxx_messageInfo_GetBlocks.Size(m)
}
func (m *GetBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlocks proto.InternalMessageInfo

func (m *GetBlocks) GetStartBlockHashes() [][]byte {
	if m != nil {
		return m.StartBlockHashes
	}
	return nil
}

type ReturnBlocks struct {
	Blocks               []*pb.Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReturnBlocks) Reset()         { *m = ReturnBlocks{} }
func (m *ReturnBlocks) String() string { return proto.CompactTextString(m) }
func (*ReturnBlocks) ProtoMessage()    {}
func (*ReturnBlocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_823c192163b402a3, []int{4}
}

func (m *ReturnBlocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBlocks.Unmarshal(m, b)
}
func (m *ReturnBlocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBlocks.Marshal(b, m, deterministic)
}
func (m *ReturnBlocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBlocks.Merge(m, src)
}
func (m *ReturnBlocks) XXX_Size() int {
	return xxx_messageInfo_ReturnBlocks.Size(m)
}
func (m *ReturnBlocks) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBlocks.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBlocks proto.InternalMessageInfo

func (m *ReturnBlocks) GetBlocks() []*pb.Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func init() {
	proto.RegisterType((*Dapmsg)(nil), "networkpb.Dapmsg")
	proto.RegisterType((*GetBlockchainInfo)(nil), "networkpb.GetBlockchainInfo")
	proto.RegisterType((*ReturnBlockchainInfo)(nil), "networkpb.ReturnBlockchainInfo")
	proto.RegisterType((*GetBlocks)(nil), "networkpb.GetBlocks")
	proto.RegisterType((*ReturnBlocks)(nil), "networkpb.ReturnBlocks")
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/network/pb/dapmsg.proto", fileDescriptor_823c192163b402a3)
}

var fileDescriptor_823c192163b402a3 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x51, 0x6b, 0xdb, 0x30,
	0x14, 0x85, 0xf1, 0xec, 0x79, 0xf8, 0xc6, 0x19, 0x99, 0xd8, 0x83, 0x18, 0x7b, 0x30, 0x26, 0x1b,
	0x66, 0x10, 0x87, 0x6d, 0x84, 0xbd, 0x87, 0xc1, 0xb2, 0xa7, 0x81, 0xd8, 0x1f, 0x90, 0x65, 0xd5,
	0x16, 0x8e, 0x25, 0x23, 0xc9, 0x69, 0x03, 0xfd, 0x41, 0xfd, 0x99, 0xc5, 0x8a, 0xdd, 0x26, 0x29,
	0xf4, 0xed, 0xea, 0x3b, 0x3e, 0xc7, 0x87, 0x7b, 0x61, 0x53, 0x09, 0x5b, 0xf7, 0x45, 0xce, 0x54,
	0xbb, 0x2e, 0x69, 0xd7, 0xed, 0xf9, 0x71, 0x5d, 0xa9, 0xd5, 0x34, 0x4a, 0x6e, 0x6f, 0x95, 0x6e,
	0xd6, 0x5d, 0x31, 0xa8, 0xad, 0xa9, 0xf2, 0x4e, 0x2b, 0xab, 0x50, 0x34, 0x0a, 0x5d, 0xf1, 0xe9,
	0xfb, 0xeb, 0x09, 0x4c, 0x69, 0x3e, 0xd8, 0x8b, 0xbd, 0x62, 0xcd, 0xc9, 0x9d, 0x3e, 0x78, 0x10,
	0xfe, 0x76, 0x71, 0x68, 0x01, 0x3e, 0x6b, 0x4b, 0xec, 0x25, 0x5e, 0x16, 0x91, 0x61, 0x44, 0x08,
	0x82, 0x92, 0x5a, 0x8a, 0xdf, 0x24, 0x5e, 0x16, 0x13, 0x37, 0xa3, 0x25, 0xcc, 0x7b, 0x29, 0xee,
	0xfe, 0x8b, 0x96, 0x13, 0xce, 0x0e, 0x25, 0xf6, 0x13, 0x2f, 0xf3, 0xc9, 0x25, 0x1c, 0xb2, 0x1a,
	0x7e, 0xc4, 0xc1, 0x29, 0xab, 0xe1, 0x47, 0xf4, 0x15, 0xde, 0xf7, 0x52, 0xfc, 0xd3, 0x5b, 0xad,
	0x68, 0xc9, 0xa8, 0xb1, 0xf8, 0xad, 0x33, 0x5e, 0x51, 0x84, 0xe1, 0x1d, 0x53, 0xbd, 0xb4, 0x5c,
	0xe3, 0x30, 0xf1, 0xb2, 0x80, 0x4c, 0xcf, 0x74, 0x05, 0x1f, 0xfe, 0x70, 0xbb, 0x1d, 0xca, 0xb3,
	0x9a, 0x0a, 0xf9, 0x57, 0xde, 0xa8, 0xe1, 0xf3, 0x03, 0xd7, 0x46, 0x28, 0x39, 0x16, 0x9f, 0x9e,
	0xe9, 0x3d, 0x7c, 0x24, 0xdc, 0xf6, 0x5a, 0x5e, 0x39, 0x96, 0x30, 0xb7, 0x54, 0xec, 0x1d, 0xdd,
	0x51, 0x53, 0x3b, 0x5f, 0x4c, 0x2e, 0x21, 0x4a, 0x60, 0xe6, 0xd6, 0xb4, 0xe3, 0xa2, 0xaa, 0xad,
	0xdb, 0x40, 0x40, 0xce, 0x11, 0xfa, 0x0c, 0x91, 0x15, 0x2d, 0x37, 0x96, 0xb6, 0xdd, 0xb8, 0x84,
	0x67, 0x90, 0xfe, 0x82, 0x68, 0x2a, 0x6b, 0xd0, 0x37, 0x58, 0x18, 0x4b, 0xb5, 0x7d, 0x8a, 0xe7,
	0x06, 0x7b, 0x89, 0x9f, 0xc5, 0xe4, 0x05, 0x4f, 0x37, 0x10, 0x9f, 0xd5, 0x36, 0xe8, 0x0b, 0x84,
	0xee, 0xaf, 0x27, 0xc7, 0xec, 0xc7, 0x3c, 0x1f, 0xce, 0xd8, 0x15, 0xb9, 0xd3, 0xc9, 0x28, 0x16,
	0xa1, 0x3b, 0xe7, 0xcf, 0xc7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x89, 0x14, 0x87, 0x45, 0x02,
	0x00, 0x00,
}
