// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import network_model "github.com/dappley/go-dappley/network/network_model"

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// GetCommandHandler provides a mock function with given fields: cmd
func (_m *Subscriber) GetCommandHandler(cmd string) network_model.CommandHandlerFunc {
	ret := _m.Called(cmd)

	var r0 network_model.CommandHandlerFunc
	if rf, ok := ret.Get(0).(func(string) network_model.CommandHandlerFunc); ok {
		r0 = rf(cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(network_model.CommandHandlerFunc)
		}
	}

	return r0
}

// GetSubscribedTopics provides a mock function with given fields:
func (_m *Subscriber) GetSubscribedTopics() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// SetCommandSendCh provides a mock function with given fields: commandSendCh
func (_m *Subscriber) SetCommandSendCh(commandSendCh chan *network_model.DappSendCmdContext) {
	_m.Called(commandSendCh)
}
