// Code generated by mockery v1.0.0. DO NOT EDIT.

package core 

import mock "github.com/stretchr/testify/mock"

// ScEngineMock is an autogenerated mock type for the ScEngineMock type
type ScEngineMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: function, args
func (_m *ScEngineMock) Execute(function string, args string) string {
	ret := _m.Called(function, args)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(function, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetGeneratedTXs provides a mock function with given fields:
func (_m *ScEngineMock) GetGeneratedTXs() []*Transaction {
	ret := _m.Called()

	var r0 []*Transaction
	if rf, ok := ret.Get(0).(func() []*Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Transaction)
		}
	}

	return r0
}

// ImportContractAddr provides a mock function with given fields: contractAddr
func (_m *ScEngineMock) ImportContractAddr(contractAddr Address) {
	_m.Called(contractAddr)
}

// ImportLocalStorage provides a mock function with given fields: storage
func (_m *ScEngineMock) ImportLocalStorage(storage map[string]string) {
	_m.Called(storage)
}

// ImportRewardStorage provides a mock function with given fields: rewards
func (_m *ScEngineMock) ImportRewardStorage(rewards map[string]string) {
	_m.Called(rewards)
}

// ImportSourceCode provides a mock function with given fields: source
func (_m *ScEngineMock) ImportSourceCode(source string) {
	_m.Called(source)
}

// ImportSourceTXID provides a mock function with given fields: txid
func (_m *ScEngineMock) ImportSourceTXID(txid []byte) {
	_m.Called(txid)
}

// ImportTransaction provides a mock function with given fields: tx
func (_m *ScEngineMock) ImportTransaction(tx *Transaction) {
	_m.Called(tx)
}

// ImportUTXOs provides a mock function with given fields: utxos
func (_m *ScEngineMock) ImportUTXOs(utxos []*UTXO) {
	_m.Called(utxos)
}
