// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import core "github.com/dappley/go-dappley/core"
import mock "github.com/stretchr/testify/mock"

// ScEngine is an autogenerated mock type for the ScEngine type
type ScEngine struct {
	mock.Mock
}

// Execute provides a mock function with given fields: function, args
func (_m *ScEngine) Execute(function string, args string) string {
	ret := _m.Called(function, args)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(function, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetGeneratedTXs provides a mock function with given fields:
func (_m *ScEngine) GetGeneratedTXs() []*core.Transaction {
	ret := _m.Called()

	var r0 []*core.Transaction
	if rf, ok := ret.Get(0).(func() []*core.Transaction); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Transaction)
		}
	}

	return r0
}

// ImportContractAddr provides a mock function with given fields: contractAddr
func (_m *ScEngine) ImportContractAddr(contractAddr core.Address) {
	_m.Called(contractAddr)
}

// ImportLocalStorage provides a mock function with given fields: storage
func (_m *ScEngine) ImportLocalStorage(storage map[string]string) {
	_m.Called(storage)
}

// ImportRewardStorage provides a mock function with given fields: rewards
func (_m *ScEngine) ImportRewardStorage(rewards map[string]string) {
	_m.Called(rewards)
}

// ImportSourceCode provides a mock function with given fields: source
func (_m *ScEngine) ImportSourceCode(source string) {
	_m.Called(source)
}

// ImportSourceTXID provides a mock function with given fields: txid
func (_m *ScEngine) ImportSourceTXID(txid []byte) {
	_m.Called(txid)
}

// ImportTransaction provides a mock function with given fields: tx
func (_m *ScEngine) ImportTransaction(tx *core.Transaction) {
	_m.Called(tx)
}

// ImportUTXOs provides a mock function with given fields: utxos
func (_m *ScEngine) ImportUTXOs(utxos []*core.UTXO) {
	_m.Called(utxos)
}
