// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: github.com/dappley/go-dappley/core/scState/pb/scState.proto

package scstatepb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State map[string]string `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

type ScState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States map[string]*State `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ScState) Reset() {
	*x = ScState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScState) ProtoMessage() {}

func (x *ScState) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScState.ProtoReflect.Descriptor instead.
func (*ScState) Descriptor() ([]byte, []int) {
	return file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescGZIP(), []int{1}
}

func (x *ScState) GetStates() map[string]*State {
	if x != nil {
		return x.States
	}
	return nil
}

type Log struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log map[string]string `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Log) Reset() {
	*x = Log{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetLog() map[string]string {
	if x != nil {
		return x.Log
	}
	return nil
}

type ChangeLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log map[string]*Log `protobuf:"bytes,1,rep,name=log,proto3" json:"log,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ChangeLog) Reset() {
	*x = ChangeLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeLog) ProtoMessage() {}

func (x *ChangeLog) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeLog.ProtoReflect.Descriptor instead.
func (*ChangeLog) Descriptor() ([]byte, []int) {
	return file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeLog) GetLog() map[string]*Log {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_github_com_dappley_go_dappley_core_scState_pb_scState_proto protoreflect.FileDescriptor

var file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDesc = []byte{
	0x0a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x70,
	0x70, 0x6c, 0x65, 0x79, 0x2f, 0x67, 0x6f, 0x2d, 0x64, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x79, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2f, 0x70, 0x62, 0x2f,
	0x73, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73,
	0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70, 0x62, 0x22, 0x74, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8e,
	0x01, 0x0a, 0x07, 0x53, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x63, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x63, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x73, 0x1a, 0x4b, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x68, 0x0a, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x29, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70, 0x62, 0x2e,
	0x4c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x03, 0x6c, 0x6f,
	0x67, 0x1a, 0x36, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x84, 0x01, 0x0a, 0x09, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x12, 0x2f, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x1a, 0x46, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescOnce sync.Once
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescData = file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDesc
)

func file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescGZIP() []byte {
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescOnce.Do(func() {
		file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescData)
	})
	return file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDescData
}

var file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_goTypes = []interface{}{
	(*State)(nil),     // 0: scstatepb.State
	(*ScState)(nil),   // 1: scstatepb.ScState
	(*Log)(nil),       // 2: scstatepb.Log
	(*ChangeLog)(nil), // 3: scstatepb.ChangeLog
	nil,               // 4: scstatepb.State.StateEntry
	nil,               // 5: scstatepb.ScState.StatesEntry
	nil,               // 6: scstatepb.Log.LogEntry
	nil,               // 7: scstatepb.ChangeLog.LogEntry
}
var file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_depIdxs = []int32{
	4, // 0: scstatepb.State.state:type_name -> scstatepb.State.StateEntry
	5, // 1: scstatepb.ScState.states:type_name -> scstatepb.ScState.StatesEntry
	6, // 2: scstatepb.Log.log:type_name -> scstatepb.Log.LogEntry
	7, // 3: scstatepb.ChangeLog.log:type_name -> scstatepb.ChangeLog.LogEntry
	0, // 4: scstatepb.ScState.StatesEntry.value:type_name -> scstatepb.State
	2, // 5: scstatepb.ChangeLog.LogEntry.value:type_name -> scstatepb.Log
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_init() }
func file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_init() {
	if File_github_com_dappley_go_dappley_core_scState_pb_scState_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Log); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_goTypes,
		DependencyIndexes: file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_depIdxs,
		MessageInfos:      file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_msgTypes,
	}.Build()
	File_github_com_dappley_go_dappley_core_scState_pb_scState_proto = out.File
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_rawDesc = nil
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_goTypes = nil
	file_github_com_dappley_go_dappley_core_scState_pb_scState_proto_depIdxs = nil
}
