// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import block "github.com/dappley/go-dappley/core/block"

import deadline "github.com/dappley/go-dappley/common/deadline"
import mock "github.com/stretchr/testify/mock"

// Consensus is an autogenerated mock type for the Consensus type
type Consensus struct {
	mock.Mock
}

// ProduceBlock provides a mock function with given fields: ProduceBlockFunc
func (_m *Consensus) ProduceBlock(ProduceBlockFunc func(func(*block.Block), deadline.Deadline)) {
	_m.Called(ProduceBlockFunc)
}

// Validate provides a mock function with given fields: blk
func (_m *Consensus) Validate(blk *block.Block) bool {
	ret := _m.Called(blk)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*block.Block) bool); ok {
		r0 = rf(blk)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
