// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package configpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	ConsensusConfig      *ConsensusConfig `protobuf:"bytes,1,opt,name=consensus_config,json=consensusConfig,proto3" json:"consensus_config,omitempty"`
	NodeConfig           *NodeConfig      `protobuf:"bytes,2,opt,name=node_config,json=nodeConfig,proto3" json:"node_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetConsensusConfig() *ConsensusConfig {
	if m != nil {
		return m.ConsensusConfig
	}
	return nil
}

func (m *Config) GetNodeConfig() *NodeConfig {
	if m != nil {
		return m.NodeConfig
	}
	return nil
}

type ConsensusConfig struct {
	MinerAddress         string   `protobuf:"bytes,1,opt,name=miner_address,json=minerAddress,proto3" json:"miner_address,omitempty"`
	PrivateKey           string   `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusConfig) Reset()         { *m = ConsensusConfig{} }
func (m *ConsensusConfig) String() string { return proto.CompactTextString(m) }
func (*ConsensusConfig) ProtoMessage()    {}
func (*ConsensusConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *ConsensusConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusConfig.Unmarshal(m, b)
}
func (m *ConsensusConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusConfig.Marshal(b, m, deterministic)
}
func (m *ConsensusConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusConfig.Merge(m, src)
}
func (m *ConsensusConfig) XXX_Size() int {
	return xxx_messageInfo_ConsensusConfig.Size(m)
}
func (m *ConsensusConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusConfig proto.InternalMessageInfo

func (m *ConsensusConfig) GetMinerAddress() string {
	if m != nil {
		return m.MinerAddress
	}
	return ""
}

func (m *ConsensusConfig) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

type NodeConfig struct {
	Port                   uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Seed                   []string `protobuf:"bytes,2,rep,name=seed,proto3" json:"seed,omitempty"`
	DbPath                 string   `protobuf:"bytes,3,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	RpcPort                uint32   `protobuf:"varint,4,opt,name=rpc_port,json=rpcPort,proto3" json:"rpc_port,omitempty"`
	Key                    string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	TxPoolLimit            uint32   `protobuf:"varint,6,opt,name=tx_pool_limit,json=txPoolLimit,proto3" json:"tx_pool_limit,omitempty"`
	BlkSizeLimit           uint32   `protobuf:"varint,7,opt,name=blk_size_limit,json=blkSizeLimit,proto3" json:"blk_size_limit,omitempty"`
	GenesisPath            string   `protobuf:"bytes,9,opt,name=genesis_path,json=genesisPath,proto3" json:"genesis_path,omitempty"`
	MetricsPollingInterval int64    `protobuf:"varint,12,opt,name=metrics_polling_interval,json=metricsPollingInterval,proto3" json:"metrics_polling_interval,omitempty"`
	MetricsInterval        int64    `protobuf:"varint,13,opt,name=metrics_interval,json=metricsInterval,proto3" json:"metrics_interval,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (m *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(m, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *NodeConfig) GetSeed() []string {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *NodeConfig) GetDbPath() string {
	if m != nil {
		return m.DbPath
	}
	return ""
}

func (m *NodeConfig) GetRpcPort() uint32 {
	if m != nil {
		return m.RpcPort
	}
	return 0
}

func (m *NodeConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *NodeConfig) GetTxPoolLimit() uint32 {
	if m != nil {
		return m.TxPoolLimit
	}
	return 0
}

func (m *NodeConfig) GetBlkSizeLimit() uint32 {
	if m != nil {
		return m.BlkSizeLimit
	}
	return 0
}

func (m *NodeConfig) GetGenesisPath() string {
	if m != nil {
		return m.GenesisPath
	}
	return ""
}

func (m *NodeConfig) GetMetricsPollingInterval() int64 {
	if m != nil {
		return m.MetricsPollingInterval
	}
	return 0
}

func (m *NodeConfig) GetMetricsInterval() int64 {
	if m != nil {
		return m.MetricsInterval
	}
	return 0
}

type DynastyConfig struct {
	Producers            []string `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	MaxProducers         uint32   `protobuf:"varint,2,opt,name=max_producers,json=maxProducers,proto3" json:"max_producers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynastyConfig) Reset()         { *m = DynastyConfig{} }
func (m *DynastyConfig) String() string { return proto.CompactTextString(m) }
func (*DynastyConfig) ProtoMessage()    {}
func (*DynastyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *DynastyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynastyConfig.Unmarshal(m, b)
}
func (m *DynastyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynastyConfig.Marshal(b, m, deterministic)
}
func (m *DynastyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynastyConfig.Merge(m, src)
}
func (m *DynastyConfig) XXX_Size() int {
	return xxx_messageInfo_DynastyConfig.Size(m)
}
func (m *DynastyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DynastyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DynastyConfig proto.InternalMessageInfo

func (m *DynastyConfig) GetProducers() []string {
	if m != nil {
		return m.Producers
	}
	return nil
}

func (m *DynastyConfig) GetMaxProducers() uint32 {
	if m != nil {
		return m.MaxProducers
	}
	return 0
}

type CliConfig struct {
	Port                 uint32   `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliConfig) Reset()         { *m = CliConfig{} }
func (m *CliConfig) String() string { return proto.CompactTextString(m) }
func (*CliConfig) ProtoMessage()    {}
func (*CliConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *CliConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliConfig.Unmarshal(m, b)
}
func (m *CliConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliConfig.Marshal(b, m, deterministic)
}
func (m *CliConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliConfig.Merge(m, src)
}
func (m *CliConfig) XXX_Size() int {
	return xxx_messageInfo_CliConfig.Size(m)
}
func (m *CliConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_CliConfig.DiscardUnknown(m)
}

var xxx_messageInfo_CliConfig proto.InternalMessageInfo

func (m *CliConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *CliConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "configpb.Config")
	proto.RegisterType((*ConsensusConfig)(nil), "configpb.ConsensusConfig")
	proto.RegisterType((*NodeConfig)(nil), "configpb.NodeConfig")
	proto.RegisterType((*DynastyConfig)(nil), "configpb.DynastyConfig")
	proto.RegisterType((*CliConfig)(nil), "configpb.CliConfig")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x8f, 0xd3, 0x30,
	0x10, 0x85, 0xd5, 0x76, 0xe9, 0x36, 0x93, 0x84, 0x56, 0x16, 0x82, 0x2c, 0x42, 0xa2, 0x04, 0x0e,
	0xe5, 0xd2, 0x03, 0x08, 0x09, 0x89, 0x13, 0xea, 0x5e, 0x10, 0x08, 0x45, 0xe1, 0xc0, 0xd1, 0x72,
	0x62, 0xd3, 0xb5, 0xea, 0xda, 0x96, 0xed, 0x5d, 0xda, 0xbd, 0xf3, 0xef, 0xf8, 0x51, 0x28, 0x13,
	0xa7, 0x15, 0x1c, 0xb8, 0x8d, 0x3f, 0xbf, 0xf7, 0x66, 0xe2, 0x09, 0x64, 0xad, 0xd1, 0x3f, 0xe4,
	0x76, 0x6d, 0x9d, 0x09, 0x86, 0xcc, 0xfa, 0x93, 0x6d, 0xca, 0x5f, 0x23, 0x98, 0x6e, 0xf0, 0x40,
	0xae, 0x61, 0xd1, 0x1a, 0xed, 0x85, 0xf6, 0xb7, 0x9e, 0xf6, 0x82, 0x62, 0xb4, 0x1c, 0xad, 0xd2,
	0x37, 0x57, 0xeb, 0x41, 0xbf, 0xde, 0x0c, 0x8a, 0xde, 0x54, 0xcf, 0xdb, 0xbf, 0x01, 0x79, 0x07,
	0xa9, 0x36, 0x5c, 0x0c, 0x01, 0x63, 0x0c, 0x78, 0x74, 0x0e, 0xf8, 0x6a, 0xb8, 0x88, 0x5e, 0xd0,
	0xa7, 0xba, 0xfc, 0x0e, 0xf3, 0x7f, 0xa2, 0xc9, 0x4b, 0xc8, 0xf7, 0x52, 0x0b, 0x47, 0x19, 0xe7,
	0x4e, 0x78, 0x8f, 0xc3, 0x24, 0x75, 0x86, 0xf0, 0x63, 0xcf, 0xc8, 0x73, 0x48, 0xad, 0x93, 0x77,
	0x2c, 0x08, 0xba, 0x13, 0x47, 0x6c, 0x97, 0xd4, 0x10, 0xd1, 0x67, 0x71, 0x2c, 0x7f, 0x8f, 0x01,
	0xce, 0x3d, 0x09, 0x81, 0x0b, 0x6b, 0x5c, 0xc0, 0xac, 0xbc, 0xc6, 0xba, 0x63, 0x5e, 0x08, 0x5e,
	0x8c, 0x97, 0x93, 0x55, 0x52, 0x63, 0x4d, 0x9e, 0xc0, 0x25, 0x6f, 0xa8, 0x65, 0xe1, 0xa6, 0x98,
	0x60, 0xe6, 0x94, 0x37, 0x15, 0x0b, 0x37, 0xe4, 0x0a, 0x66, 0xce, 0xb6, 0x14, 0x43, 0x2e, 0x30,
	0xe4, 0xd2, 0xd9, 0xb6, 0xea, 0x72, 0x16, 0x30, 0xe9, 0x66, 0x78, 0x80, 0xfa, 0xae, 0x24, 0x25,
	0xe4, 0xe1, 0x40, 0xad, 0x31, 0x8a, 0x2a, 0xb9, 0x97, 0xa1, 0x98, 0xa2, 0x23, 0x0d, 0x87, 0xca,
	0x18, 0xf5, 0xa5, 0x43, 0xe4, 0x15, 0x3c, 0x6c, 0xd4, 0x8e, 0x7a, 0x79, 0x2f, 0xa2, 0xe8, 0x12,
	0x45, 0x59, 0xa3, 0x76, 0xdf, 0xe4, 0xbd, 0xe8, 0x55, 0x2f, 0x20, 0xdb, 0x0a, 0x2d, 0xbc, 0xf4,
	0xfd, 0x50, 0x09, 0x36, 0x49, 0x23, 0xc3, 0xc9, 0xde, 0x43, 0xb1, 0x17, 0xc1, 0xc9, 0xd6, 0x53,
	0x6b, 0x94, 0x92, 0x7a, 0x4b, 0xa5, 0x0e, 0xc2, 0xdd, 0x31, 0x55, 0x64, 0xcb, 0xd1, 0x6a, 0x52,
	0x3f, 0x8e, 0xf7, 0x55, 0x7f, 0xfd, 0x29, 0xde, 0x92, 0xd7, 0xb0, 0x18, 0x9c, 0x27, 0x47, 0x8e,
	0x8e, 0x79, 0xe4, 0x83, 0xb4, 0xac, 0x21, 0xbf, 0x3e, 0x6a, 0xe6, 0xc3, 0x31, 0x3e, 0xe8, 0x33,
	0x48, 0xac, 0x33, 0xfc, 0xb6, 0x15, 0xae, 0xdb, 0x50, 0xf7, 0x82, 0x67, 0x80, 0x3b, 0x64, 0x07,
	0x7a, 0x56, 0x8c, 0xfb, 0x6f, 0xdb, 0xb3, 0x43, 0x35, 0xb0, 0xf2, 0x03, 0x24, 0x1b, 0x25, 0xff,
	0xb3, 0xa0, 0xa7, 0x30, 0xb3, 0xcc, 0xfb, 0x9f, 0xc6, 0xf1, 0xb8, 0xe1, 0xd3, 0xb9, 0x99, 0xe2,
	0x1f, 0xfd, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0x59, 0xf8, 0xa2, 0xe1, 0x02, 0x00,
	0x00,
}
