// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/dappley/go-dappley/rpc/pb/rpc.proto

package rpcpb

import (
	fmt "fmt"
	pb1 "github.com/dappley/go-dappley/core/pb"
	pb "github.com/dappley/go-dappley/network/pb"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message
type CreateWalletRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWalletRequest) Reset()         { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()    {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{0}
}

func (m *CreateWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWalletRequest.Unmarshal(m, b)
}
func (m *CreateWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWalletRequest.Marshal(b, m, deterministic)
}
func (m *CreateWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWalletRequest.Merge(m, src)
}
func (m *CreateWalletRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWalletRequest.Size(m)
}
func (m *CreateWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWalletRequest proto.InternalMessageInfo

func (m *CreateWalletRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateWalletRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UnlockWalletRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockWalletRequest) Reset()         { *m = UnlockWalletRequest{} }
func (m *UnlockWalletRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockWalletRequest) ProtoMessage()    {}
func (*UnlockWalletRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{1}
}

func (m *UnlockWalletRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockWalletRequest.Unmarshal(m, b)
}
func (m *UnlockWalletRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockWalletRequest.Marshal(b, m, deterministic)
}
func (m *UnlockWalletRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockWalletRequest.Merge(m, src)
}
func (m *UnlockWalletRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockWalletRequest.Size(m)
}
func (m *UnlockWalletRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockWalletRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockWalletRequest proto.InternalMessageInfo

func (m *UnlockWalletRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnlockWalletResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockWalletResponse) Reset()         { *m = UnlockWalletResponse{} }
func (m *UnlockWalletResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockWalletResponse) ProtoMessage()    {}
func (*UnlockWalletResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{2}
}

func (m *UnlockWalletResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockWalletResponse.Unmarshal(m, b)
}
func (m *UnlockWalletResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockWalletResponse.Marshal(b, m, deterministic)
}
func (m *UnlockWalletResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockWalletResponse.Merge(m, src)
}
func (m *UnlockWalletResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockWalletResponse.Size(m)
}
func (m *UnlockWalletResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockWalletResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockWalletResponse proto.InternalMessageInfo

func (m *UnlockWalletResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddProducerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProducerRequest) Reset()         { *m = AddProducerRequest{} }
func (m *AddProducerRequest) String() string { return proto.CompactTextString(m) }
func (*AddProducerRequest) ProtoMessage()    {}
func (*AddProducerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{3}
}

func (m *AddProducerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProducerRequest.Unmarshal(m, b)
}
func (m *AddProducerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProducerRequest.Marshal(b, m, deterministic)
}
func (m *AddProducerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProducerRequest.Merge(m, src)
}
func (m *AddProducerRequest) XXX_Size() int {
	return xxx_messageInfo_AddProducerRequest.Size(m)
}
func (m *AddProducerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProducerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProducerRequest proto.InternalMessageInfo

func (m *AddProducerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddProducerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetBalanceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceRequest) Reset()         { *m = GetBalanceRequest{} }
func (m *GetBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*GetBalanceRequest) ProtoMessage()    {}
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{4}
}

func (m *GetBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceRequest.Unmarshal(m, b)
}
func (m *GetBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceRequest.Marshal(b, m, deterministic)
}
func (m *GetBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceRequest.Merge(m, src)
}
func (m *GetBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_GetBalanceRequest.Size(m)
}
func (m *GetBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceRequest proto.InternalMessageInfo

func (m *GetBalanceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBalanceRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *GetBalanceRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SendFromMinerRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFromMinerRequest) Reset()         { *m = SendFromMinerRequest{} }
func (m *SendFromMinerRequest) String() string { return proto.CompactTextString(m) }
func (*SendFromMinerRequest) ProtoMessage()    {}
func (*SendFromMinerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{5}
}

func (m *SendFromMinerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFromMinerRequest.Unmarshal(m, b)
}
func (m *SendFromMinerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFromMinerRequest.Marshal(b, m, deterministic)
}
func (m *SendFromMinerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFromMinerRequest.Merge(m, src)
}
func (m *SendFromMinerRequest) XXX_Size() int {
	return xxx_messageInfo_SendFromMinerRequest.Size(m)
}
func (m *SendFromMinerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFromMinerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendFromMinerRequest proto.InternalMessageInfo

func (m *SendFromMinerRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendFromMinerRequest) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type SendRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount               []byte   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Walletpath           string   `protobuf:"bytes,4,opt,name=Walletpath,proto3" json:"Walletpath,omitempty"`
	Tip                  uint64   `protobuf:"varint,5,opt,name=tip,proto3" json:"tip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{6}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendRequest) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *SendRequest) GetWalletpath() string {
	if m != nil {
		return m.Walletpath
	}
	return ""
}

func (m *SendRequest) GetTip() uint64 {
	if m != nil {
		return m.Tip
	}
	return 0
}

type GetWalletAddressRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletAddressRequest) Reset()         { *m = GetWalletAddressRequest{} }
func (m *GetWalletAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetWalletAddressRequest) ProtoMessage()    {}
func (*GetWalletAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{7}
}

func (m *GetWalletAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletAddressRequest.Unmarshal(m, b)
}
func (m *GetWalletAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetWalletAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletAddressRequest.Merge(m, src)
}
func (m *GetWalletAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetWalletAddressRequest.Size(m)
}
func (m *GetWalletAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletAddressRequest proto.InternalMessageInfo

func (m *GetWalletAddressRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWalletAddressRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type GetPeerInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeerInfoRequest) Reset()         { *m = GetPeerInfoRequest{} }
func (m *GetPeerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetPeerInfoRequest) ProtoMessage()    {}
func (*GetPeerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{8}
}

func (m *GetPeerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeerInfoRequest.Unmarshal(m, b)
}
func (m *GetPeerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeerInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetPeerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeerInfoRequest.Merge(m, src)
}
func (m *GetPeerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetPeerInfoRequest.Size(m)
}
func (m *GetPeerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeerInfoRequest proto.InternalMessageInfo

type GetBlockchainInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainInfoRequest) Reset()         { *m = GetBlockchainInfoRequest{} }
func (m *GetBlockchainInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainInfoRequest) ProtoMessage()    {}
func (*GetBlockchainInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{9}
}

func (m *GetBlockchainInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainInfoRequest.Unmarshal(m, b)
}
func (m *GetBlockchainInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockchainInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainInfoRequest.Merge(m, src)
}
func (m *GetBlockchainInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainInfoRequest.Size(m)
}
func (m *GetBlockchainInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainInfoRequest proto.InternalMessageInfo

type AddPeerRequest struct {
	FullAddress          string   `protobuf:"bytes,1,opt,name=fullAddress,proto3" json:"fullAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPeerRequest) Reset()         { *m = AddPeerRequest{} }
func (m *AddPeerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPeerRequest) ProtoMessage()    {}
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{10}
}

func (m *AddPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerRequest.Unmarshal(m, b)
}
func (m *AddPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerRequest.Marshal(b, m, deterministic)
}
func (m *AddPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerRequest.Merge(m, src)
}
func (m *AddPeerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPeerRequest.Size(m)
}
func (m *AddPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerRequest proto.InternalMessageInfo

func (m *AddPeerRequest) GetFullAddress() string {
	if m != nil {
		return m.FullAddress
	}
	return ""
}

type AddProducerResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProducerResponse) Reset()         { *m = AddProducerResponse{} }
func (m *AddProducerResponse) String() string { return proto.CompactTextString(m) }
func (*AddProducerResponse) ProtoMessage()    {}
func (*AddProducerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{11}
}

func (m *AddProducerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProducerResponse.Unmarshal(m, b)
}
func (m *AddProducerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProducerResponse.Marshal(b, m, deterministic)
}
func (m *AddProducerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProducerResponse.Merge(m, src)
}
func (m *AddProducerResponse) XXX_Size() int {
	return xxx_messageInfo_AddProducerResponse.Size(m)
}
func (m *AddProducerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProducerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProducerResponse proto.InternalMessageInfo

func (m *AddProducerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetBalanceResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBalanceResponse) Reset()         { *m = GetBalanceResponse{} }
func (m *GetBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*GetBalanceResponse) ProtoMessage()    {}
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{12}
}

func (m *GetBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBalanceResponse.Unmarshal(m, b)
}
func (m *GetBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBalanceResponse.Marshal(b, m, deterministic)
}
func (m *GetBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBalanceResponse.Merge(m, src)
}
func (m *GetBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_GetBalanceResponse.Size(m)
}
func (m *GetBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBalanceResponse proto.InternalMessageInfo

func (m *GetBalanceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetBalanceResponse) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SendFromMinerResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendFromMinerResponse) Reset()         { *m = SendFromMinerResponse{} }
func (m *SendFromMinerResponse) String() string { return proto.CompactTextString(m) }
func (*SendFromMinerResponse) ProtoMessage()    {}
func (*SendFromMinerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{13}
}

func (m *SendFromMinerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendFromMinerResponse.Unmarshal(m, b)
}
func (m *SendFromMinerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendFromMinerResponse.Marshal(b, m, deterministic)
}
func (m *SendFromMinerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendFromMinerResponse.Merge(m, src)
}
func (m *SendFromMinerResponse) XXX_Size() int {
	return xxx_messageInfo_SendFromMinerResponse.Size(m)
}
func (m *SendFromMinerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendFromMinerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendFromMinerResponse proto.InternalMessageInfo

func (m *SendFromMinerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{14}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPeerInfoResponse struct {
	PeerList             *pb.Peerlist `protobuf:"bytes,1,opt,name=peerList,proto3" json:"peerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPeerInfoResponse) Reset()         { *m = GetPeerInfoResponse{} }
func (m *GetPeerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetPeerInfoResponse) ProtoMessage()    {}
func (*GetPeerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{15}
}

func (m *GetPeerInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeerInfoResponse.Unmarshal(m, b)
}
func (m *GetPeerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeerInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetPeerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeerInfoResponse.Merge(m, src)
}
func (m *GetPeerInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetPeerInfoResponse.Size(m)
}
func (m *GetPeerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeerInfoResponse proto.InternalMessageInfo

func (m *GetPeerInfoResponse) GetPeerList() *pb.Peerlist {
	if m != nil {
		return m.PeerList
	}
	return nil
}

type GetBlockchainInfoResponse struct {
	TailBlockHash        []byte   `protobuf:"bytes,1,opt,name=tailBlockHash,proto3" json:"tailBlockHash,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,2,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Producers            []string `protobuf:"bytes,3,rep,name=producers,proto3" json:"producers,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockchainInfoResponse) Reset()         { *m = GetBlockchainInfoResponse{} }
func (m *GetBlockchainInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockchainInfoResponse) ProtoMessage()    {}
func (*GetBlockchainInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{16}
}

func (m *GetBlockchainInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockchainInfoResponse.Unmarshal(m, b)
}
func (m *GetBlockchainInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockchainInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockchainInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockchainInfoResponse.Merge(m, src)
}
func (m *GetBlockchainInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockchainInfoResponse.Size(m)
}
func (m *GetBlockchainInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockchainInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockchainInfoResponse proto.InternalMessageInfo

func (m *GetBlockchainInfoResponse) GetTailBlockHash() []byte {
	if m != nil {
		return m.TailBlockHash
	}
	return nil
}

func (m *GetBlockchainInfoResponse) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *GetBlockchainInfoResponse) GetProducers() []string {
	if m != nil {
		return m.Producers
	}
	return nil
}

func (m *GetBlockchainInfoResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type AddPeerResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPeerResponse) Reset()         { *m = AddPeerResponse{} }
func (m *AddPeerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPeerResponse) ProtoMessage()    {}
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{17}
}

func (m *AddPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerResponse.Unmarshal(m, b)
}
func (m *AddPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerResponse.Marshal(b, m, deterministic)
}
func (m *AddPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerResponse.Merge(m, src)
}
func (m *AddPeerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPeerResponse.Size(m)
}
func (m *AddPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerResponse proto.InternalMessageInfo

func (m *AddPeerResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetVersionRequest struct {
	ProtoVersion         string   `protobuf:"bytes,1,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionRequest) Reset()         { *m = GetVersionRequest{} }
func (m *GetVersionRequest) String() string { return proto.CompactTextString(m) }
func (*GetVersionRequest) ProtoMessage()    {}
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{18}
}

func (m *GetVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionRequest.Unmarshal(m, b)
}
func (m *GetVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionRequest.Marshal(b, m, deterministic)
}
func (m *GetVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionRequest.Merge(m, src)
}
func (m *GetVersionRequest) XXX_Size() int {
	return xxx_messageInfo_GetVersionRequest.Size(m)
}
func (m *GetVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionRequest proto.InternalMessageInfo

func (m *GetVersionRequest) GetProtoVersion() string {
	if m != nil {
		return m.ProtoVersion
	}
	return ""
}

type GetVersionResponse struct {
	ErrorCode            uint32   `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ProtoVersion         string   `protobuf:"bytes,2,opt,name=protoVersion,proto3" json:"protoVersion,omitempty"`
	ServerVersion        string   `protobuf:"bytes,3,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVersionResponse) Reset()         { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()    {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{19}
}

func (m *GetVersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVersionResponse.Unmarshal(m, b)
}
func (m *GetVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVersionResponse.Marshal(b, m, deterministic)
}
func (m *GetVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVersionResponse.Merge(m, src)
}
func (m *GetVersionResponse) XXX_Size() int {
	return xxx_messageInfo_GetVersionResponse.Size(m)
}
func (m *GetVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVersionResponse proto.InternalMessageInfo

func (m *GetVersionResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetVersionResponse) GetProtoVersion() string {
	if m != nil {
		return m.ProtoVersion
	}
	return ""
}

func (m *GetVersionResponse) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

type GetUTXORequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUTXORequest) Reset()         { *m = GetUTXORequest{} }
func (m *GetUTXORequest) String() string { return proto.CompactTextString(m) }
func (*GetUTXORequest) ProtoMessage()    {}
func (*GetUTXORequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{20}
}

func (m *GetUTXORequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUTXORequest.Unmarshal(m, b)
}
func (m *GetUTXORequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUTXORequest.Marshal(b, m, deterministic)
}
func (m *GetUTXORequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUTXORequest.Merge(m, src)
}
func (m *GetUTXORequest) XXX_Size() int {
	return xxx_messageInfo_GetUTXORequest.Size(m)
}
func (m *GetUTXORequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUTXORequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUTXORequest proto.InternalMessageInfo

func (m *GetUTXORequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetUTXOResponse struct {
	ErrorCode            uint32             `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Utxos                []*UTXO            `protobuf:"bytes,2,rep,name=utxos,proto3" json:"utxos,omitempty"`
	BlockHeaders         []*pb1.BlockHeader `protobuf:"bytes,3,rep,name=blockHeaders,proto3" json:"blockHeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUTXOResponse) Reset()         { *m = GetUTXOResponse{} }
func (m *GetUTXOResponse) String() string { return proto.CompactTextString(m) }
func (*GetUTXOResponse) ProtoMessage()    {}
func (*GetUTXOResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{21}
}

func (m *GetUTXOResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUTXOResponse.Unmarshal(m, b)
}
func (m *GetUTXOResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUTXOResponse.Marshal(b, m, deterministic)
}
func (m *GetUTXOResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUTXOResponse.Merge(m, src)
}
func (m *GetUTXOResponse) XXX_Size() int {
	return xxx_messageInfo_GetUTXOResponse.Size(m)
}
func (m *GetUTXOResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUTXOResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUTXOResponse proto.InternalMessageInfo

func (m *GetUTXOResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetUTXOResponse) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func (m *GetUTXOResponse) GetBlockHeaders() []*pb1.BlockHeader {
	if m != nil {
		return m.BlockHeaders
	}
	return nil
}

type UTXO struct {
	Amount               []byte   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PublicKeyHash        []byte   `protobuf:"bytes,2,opt,name=publicKeyHash,proto3" json:"publicKeyHash,omitempty"`
	Txid                 []byte   `protobuf:"bytes,3,opt,name=txid,proto3" json:"txid,omitempty"`
	TxIndex              uint32   `protobuf:"varint,4,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UTXO) Reset()         { *m = UTXO{} }
func (m *UTXO) String() string { return proto.CompactTextString(m) }
func (*UTXO) ProtoMessage()    {}
func (*UTXO) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{22}
}

func (m *UTXO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UTXO.Unmarshal(m, b)
}
func (m *UTXO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UTXO.Marshal(b, m, deterministic)
}
func (m *UTXO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UTXO.Merge(m, src)
}
func (m *UTXO) XXX_Size() int {
	return xxx_messageInfo_UTXO.Size(m)
}
func (m *UTXO) XXX_DiscardUnknown() {
	xxx_messageInfo_UTXO.DiscardUnknown(m)
}

var xxx_messageInfo_UTXO proto.InternalMessageInfo

func (m *UTXO) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *UTXO) GetPublicKeyHash() []byte {
	if m != nil {
		return m.PublicKeyHash
	}
	return nil
}

func (m *UTXO) GetTxid() []byte {
	if m != nil {
		return m.Txid
	}
	return nil
}

func (m *UTXO) GetTxIndex() uint32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

type GetBlocksRequest struct {
	StartBlockHashes     [][]byte `protobuf:"bytes,1,rep,name=startBlockHashes,proto3" json:"startBlockHashes,omitempty"`
	MaxCount             int32    `protobuf:"varint,2,opt,name=maxCount,proto3" json:"maxCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlocksRequest) Reset()         { *m = GetBlocksRequest{} }
func (m *GetBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlocksRequest) ProtoMessage()    {}
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{23}
}

func (m *GetBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlocksRequest.Unmarshal(m, b)
}
func (m *GetBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlocksRequest.Marshal(b, m, deterministic)
}
func (m *GetBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlocksRequest.Merge(m, src)
}
func (m *GetBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlocksRequest.Size(m)
}
func (m *GetBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlocksRequest proto.InternalMessageInfo

func (m *GetBlocksRequest) GetStartBlockHashes() [][]byte {
	if m != nil {
		return m.StartBlockHashes
	}
	return nil
}

func (m *GetBlocksRequest) GetMaxCount() int32 {
	if m != nil {
		return m.MaxCount
	}
	return 0
}

type GetBlocksResponse struct {
	ErrorCode            uint32       `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Blocks               []*pb1.Block `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetBlocksResponse) Reset()         { *m = GetBlocksResponse{} }
func (m *GetBlocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlocksResponse) ProtoMessage()    {}
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{24}
}

func (m *GetBlocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlocksResponse.Unmarshal(m, b)
}
func (m *GetBlocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlocksResponse.Marshal(b, m, deterministic)
}
func (m *GetBlocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlocksResponse.Merge(m, src)
}
func (m *GetBlocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlocksResponse.Size(m)
}
func (m *GetBlocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlocksResponse proto.InternalMessageInfo

func (m *GetBlocksResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetBlocksResponse) GetBlocks() []*pb1.Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type GetBlockByHashRequest struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHashRequest) Reset()         { *m = GetBlockByHashRequest{} }
func (m *GetBlockByHashRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashRequest) ProtoMessage()    {}
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{25}
}

func (m *GetBlockByHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashRequest.Unmarshal(m, b)
}
func (m *GetBlockByHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashRequest.Merge(m, src)
}
func (m *GetBlockByHashRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashRequest.Size(m)
}
func (m *GetBlockByHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashRequest proto.InternalMessageInfo

func (m *GetBlockByHashRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type GetBlockByHashResponse struct {
	ErrorCode            uint32     `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Block                *pb1.Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBlockByHashResponse) Reset()         { *m = GetBlockByHashResponse{} }
func (m *GetBlockByHashResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHashResponse) ProtoMessage()    {}
func (*GetBlockByHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{26}
}

func (m *GetBlockByHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHashResponse.Unmarshal(m, b)
}
func (m *GetBlockByHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHashResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockByHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHashResponse.Merge(m, src)
}
func (m *GetBlockByHashResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHashResponse.Size(m)
}
func (m *GetBlockByHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHashResponse proto.InternalMessageInfo

func (m *GetBlockByHashResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetBlockByHashResponse) GetBlock() *pb1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type GetBlockByHeightRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockByHeightRequest) Reset()         { *m = GetBlockByHeightRequest{} }
func (m *GetBlockByHeightRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightRequest) ProtoMessage()    {}
func (*GetBlockByHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{27}
}

func (m *GetBlockByHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightRequest.Unmarshal(m, b)
}
func (m *GetBlockByHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightRequest.Marshal(b, m, deterministic)
}
func (m *GetBlockByHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightRequest.Merge(m, src)
}
func (m *GetBlockByHeightRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightRequest.Size(m)
}
func (m *GetBlockByHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightRequest proto.InternalMessageInfo

func (m *GetBlockByHeightRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type GetBlockByHeightResponse struct {
	ErrorCode            uint32     `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Block                *pb1.Block `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetBlockByHeightResponse) Reset()         { *m = GetBlockByHeightResponse{} }
func (m *GetBlockByHeightResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockByHeightResponse) ProtoMessage()    {}
func (*GetBlockByHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{28}
}

func (m *GetBlockByHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockByHeightResponse.Unmarshal(m, b)
}
func (m *GetBlockByHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockByHeightResponse.Marshal(b, m, deterministic)
}
func (m *GetBlockByHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockByHeightResponse.Merge(m, src)
}
func (m *GetBlockByHeightResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockByHeightResponse.Size(m)
}
func (m *GetBlockByHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockByHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockByHeightResponse proto.InternalMessageInfo

func (m *GetBlockByHeightResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetBlockByHeightResponse) GetBlock() *pb1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type SendTransactionRequest struct {
	Transaction          *pb1.Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendTransactionRequest) Reset()         { *m = SendTransactionRequest{} }
func (m *SendTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionRequest) ProtoMessage()    {}
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{29}
}

func (m *SendTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionRequest.Unmarshal(m, b)
}
func (m *SendTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionRequest.Merge(m, src)
}
func (m *SendTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionRequest.Size(m)
}
func (m *SendTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionRequest proto.InternalMessageInfo

func (m *SendTransactionRequest) GetTransaction() *pb1.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type SendTransactionResponse struct {
	ErrorCode            uint32   `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionResponse) Reset()         { *m = SendTransactionResponse{} }
func (m *SendTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*SendTransactionResponse) ProtoMessage()    {}
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6f7014334e4682f, []int{30}
}

func (m *SendTransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionResponse.Unmarshal(m, b)
}
func (m *SendTransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionResponse.Marshal(b, m, deterministic)
}
func (m *SendTransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionResponse.Merge(m, src)
}
func (m *SendTransactionResponse) XXX_Size() int {
	return xxx_messageInfo_SendTransactionResponse.Size(m)
}
func (m *SendTransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionResponse proto.InternalMessageInfo

func (m *SendTransactionResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateWalletRequest)(nil), "rpcpb.CreateWalletRequest")
	proto.RegisterType((*UnlockWalletRequest)(nil), "rpcpb.UnlockWalletRequest")
	proto.RegisterType((*UnlockWalletResponse)(nil), "rpcpb.UnlockWalletResponse")
	proto.RegisterType((*AddProducerRequest)(nil), "rpcpb.AddProducerRequest")
	proto.RegisterType((*GetBalanceRequest)(nil), "rpcpb.GetBalanceRequest")
	proto.RegisterType((*SendFromMinerRequest)(nil), "rpcpb.SendFromMinerRequest")
	proto.RegisterType((*SendRequest)(nil), "rpcpb.SendRequest")
	proto.RegisterType((*GetWalletAddressRequest)(nil), "rpcpb.GetWalletAddressRequest")
	proto.RegisterType((*GetPeerInfoRequest)(nil), "rpcpb.GetPeerInfoRequest")
	proto.RegisterType((*GetBlockchainInfoRequest)(nil), "rpcpb.GetBlockchainInfoRequest")
	proto.RegisterType((*AddPeerRequest)(nil), "rpcpb.AddPeerRequest")
	proto.RegisterType((*AddProducerResponse)(nil), "rpcpb.AddProducerResponse")
	proto.RegisterType((*GetBalanceResponse)(nil), "rpcpb.GetBalanceResponse")
	proto.RegisterType((*SendFromMinerResponse)(nil), "rpcpb.SendFromMinerResponse")
	proto.RegisterType((*SendResponse)(nil), "rpcpb.SendResponse")
	proto.RegisterType((*GetPeerInfoResponse)(nil), "rpcpb.GetPeerInfoResponse")
	proto.RegisterType((*GetBlockchainInfoResponse)(nil), "rpcpb.GetBlockchainInfoResponse")
	proto.RegisterType((*AddPeerResponse)(nil), "rpcpb.AddPeerResponse")
	proto.RegisterType((*GetVersionRequest)(nil), "rpcpb.GetVersionRequest")
	proto.RegisterType((*GetVersionResponse)(nil), "rpcpb.GetVersionResponse")
	proto.RegisterType((*GetUTXORequest)(nil), "rpcpb.GetUTXORequest")
	proto.RegisterType((*GetUTXOResponse)(nil), "rpcpb.GetUTXOResponse")
	proto.RegisterType((*UTXO)(nil), "rpcpb.UTXO")
	proto.RegisterType((*GetBlocksRequest)(nil), "rpcpb.GetBlocksRequest")
	proto.RegisterType((*GetBlocksResponse)(nil), "rpcpb.GetBlocksResponse")
	proto.RegisterType((*GetBlockByHashRequest)(nil), "rpcpb.GetBlockByHashRequest")
	proto.RegisterType((*GetBlockByHashResponse)(nil), "rpcpb.GetBlockByHashResponse")
	proto.RegisterType((*GetBlockByHeightRequest)(nil), "rpcpb.GetBlockByHeightRequest")
	proto.RegisterType((*GetBlockByHeightResponse)(nil), "rpcpb.GetBlockByHeightResponse")
	proto.RegisterType((*SendTransactionRequest)(nil), "rpcpb.SendTransactionRequest")
	proto.RegisterType((*SendTransactionResponse)(nil), "rpcpb.SendTransactionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RpcServiceClient is the client API for RpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RpcServiceClient interface {
	RpcGetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	RpcGetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	RpcGetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*GetBlockchainInfoResponse, error)
	RpcGetUTXO(ctx context.Context, in *GetUTXORequest, opts ...grpc.CallOption) (*GetUTXOResponse, error)
	RpcGetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error)
	RpcGetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashResponse, error)
	RpcGetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightResponse, error)
	RpcSendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error)
}

type rpcServiceClient struct {
	cc *grpc.ClientConn
}

func NewRpcServiceClient(cc *grpc.ClientConn) RpcServiceClient {
	return &rpcServiceClient{cc}
}

func (c *rpcServiceClient) RpcGetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetBlockchainInfo(ctx context.Context, in *GetBlockchainInfoRequest, opts ...grpc.CallOption) (*GetBlockchainInfoResponse, error) {
	out := new(GetBlockchainInfoResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetBlockchainInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetUTXO(ctx context.Context, in *GetUTXORequest, opts ...grpc.CallOption) (*GetUTXOResponse, error) {
	out := new(GetUTXOResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetUTXO", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetBlocks(ctx context.Context, in *GetBlocksRequest, opts ...grpc.CallOption) (*GetBlocksResponse, error) {
	out := new(GetBlocksResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetBlockByHash(ctx context.Context, in *GetBlockByHashRequest, opts ...grpc.CallOption) (*GetBlockByHashResponse, error) {
	out := new(GetBlockByHashResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcGetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightResponse, error) {
	out := new(GetBlockByHeightResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcGetBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServiceClient) RpcSendTransaction(ctx context.Context, in *SendTransactionRequest, opts ...grpc.CallOption) (*SendTransactionResponse, error) {
	out := new(SendTransactionResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.RpcService/RpcSendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServiceServer is the server API for RpcService service.
type RpcServiceServer interface {
	RpcGetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	RpcGetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	RpcGetBlockchainInfo(context.Context, *GetBlockchainInfoRequest) (*GetBlockchainInfoResponse, error)
	RpcGetUTXO(context.Context, *GetUTXORequest) (*GetUTXOResponse, error)
	RpcGetBlocks(context.Context, *GetBlocksRequest) (*GetBlocksResponse, error)
	RpcGetBlockByHash(context.Context, *GetBlockByHashRequest) (*GetBlockByHashResponse, error)
	RpcGetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*GetBlockByHeightResponse, error)
	RpcSendTransaction(context.Context, *SendTransactionRequest) (*SendTransactionResponse, error)
}

func RegisterRpcServiceServer(s *grpc.Server, srv RpcServiceServer) {
	s.RegisterService(&_RpcService_serviceDesc, srv)
}

func _RpcService_RpcGetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetBlockchainInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockchainInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetBlockchainInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetBlockchainInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetBlockchainInfo(ctx, req.(*GetBlockchainInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetUTXO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUTXORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetUTXO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetUTXO",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetUTXO(ctx, req.(*GetUTXORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetBlocks(ctx, req.(*GetBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetBlockByHash(ctx, req.(*GetBlockByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcGetBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcGetBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcGetBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcGetBlockByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcService_RpcSendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServiceServer).RpcSendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.RpcService/RpcSendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServiceServer).RpcSendTransaction(ctx, req.(*SendTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RpcService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.RpcService",
	HandlerType: (*RpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcGetVersion",
			Handler:    _RpcService_RpcGetVersion_Handler,
		},
		{
			MethodName: "RpcGetBalance",
			Handler:    _RpcService_RpcGetBalance_Handler,
		},
		{
			MethodName: "RpcGetBlockchainInfo",
			Handler:    _RpcService_RpcGetBlockchainInfo_Handler,
		},
		{
			MethodName: "RpcGetUTXO",
			Handler:    _RpcService_RpcGetUTXO_Handler,
		},
		{
			MethodName: "RpcGetBlocks",
			Handler:    _RpcService_RpcGetBlocks_Handler,
		},
		{
			MethodName: "RpcGetBlockByHash",
			Handler:    _RpcService_RpcGetBlockByHash_Handler,
		},
		{
			MethodName: "RpcGetBlockByHeight",
			Handler:    _RpcService_RpcGetBlockByHeight_Handler,
		},
		{
			MethodName: "RpcSendTransaction",
			Handler:    _RpcService_RpcSendTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/dappley/go-dappley/rpc/pb/rpc.proto",
}

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	RpcAddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error)
	RpcSend(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	RpcGetPeerInfo(ctx context.Context, in *GetPeerInfoRequest, opts ...grpc.CallOption) (*GetPeerInfoResponse, error)
	RpcSendFromMiner(ctx context.Context, in *SendFromMinerRequest, opts ...grpc.CallOption) (*SendFromMinerResponse, error)
	RpcAddProducer(ctx context.Context, in *AddProducerRequest, opts ...grpc.CallOption) (*AddProducerResponse, error)
	RpcUnlockWallet(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*UnlockWalletResponse, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) RpcAddPeer(ctx context.Context, in *AddPeerRequest, opts ...grpc.CallOption) (*AddPeerResponse, error) {
	out := new(AddPeerResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcAddPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RpcSend(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RpcGetPeerInfo(ctx context.Context, in *GetPeerInfoRequest, opts ...grpc.CallOption) (*GetPeerInfoResponse, error) {
	out := new(GetPeerInfoResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcGetPeerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RpcSendFromMiner(ctx context.Context, in *SendFromMinerRequest, opts ...grpc.CallOption) (*SendFromMinerResponse, error) {
	out := new(SendFromMinerResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcSendFromMiner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RpcAddProducer(ctx context.Context, in *AddProducerRequest, opts ...grpc.CallOption) (*AddProducerResponse, error) {
	out := new(AddProducerResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcAddProducer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RpcUnlockWallet(ctx context.Context, in *UnlockWalletRequest, opts ...grpc.CallOption) (*UnlockWalletResponse, error) {
	out := new(UnlockWalletResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/RpcUnlockWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	RpcAddPeer(context.Context, *AddPeerRequest) (*AddPeerResponse, error)
	RpcSend(context.Context, *SendRequest) (*SendResponse, error)
	RpcGetPeerInfo(context.Context, *GetPeerInfoRequest) (*GetPeerInfoResponse, error)
	RpcSendFromMiner(context.Context, *SendFromMinerRequest) (*SendFromMinerResponse, error)
	RpcAddProducer(context.Context, *AddProducerRequest) (*AddProducerResponse, error)
	RpcUnlockWallet(context.Context, *UnlockWalletRequest) (*UnlockWalletResponse, error)
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_RpcAddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcAddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcAddPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcAddPeer(ctx, req.(*AddPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RpcSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcSend(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RpcGetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcGetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcGetPeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcGetPeerInfo(ctx, req.(*GetPeerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RpcSendFromMiner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFromMinerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcSendFromMiner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcSendFromMiner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcSendFromMiner(ctx, req.(*SendFromMinerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RpcAddProducer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProducerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcAddProducer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcAddProducer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcAddProducer(ctx, req.(*AddProducerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RpcUnlockWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RpcUnlockWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/RpcUnlockWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RpcUnlockWallet(ctx, req.(*UnlockWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcAddPeer",
			Handler:    _AdminService_RpcAddPeer_Handler,
		},
		{
			MethodName: "RpcSend",
			Handler:    _AdminService_RpcSend_Handler,
		},
		{
			MethodName: "RpcGetPeerInfo",
			Handler:    _AdminService_RpcGetPeerInfo_Handler,
		},
		{
			MethodName: "RpcSendFromMiner",
			Handler:    _AdminService_RpcSendFromMiner_Handler,
		},
		{
			MethodName: "RpcAddProducer",
			Handler:    _AdminService_RpcAddProducer_Handler,
		},
		{
			MethodName: "RpcUnlockWallet",
			Handler:    _AdminService_RpcUnlockWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/dappley/go-dappley/rpc/pb/rpc.proto",
}

func init() {
	proto.RegisterFile("github.com/dappley/go-dappley/rpc/pb/rpc.proto", fileDescriptor_c6f7014334e4682f)
}

var fileDescriptor_c6f7014334e4682f = []byte{
	// 1183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdf, 0x4e, 0x23, 0xb7,
	0x17, 0x26, 0x09, 0x09, 0xcb, 0x49, 0x02, 0xac, 0x03, 0x21, 0x3b, 0xcb, 0x8f, 0xe5, 0xe7, 0x6e,
	0xa5, 0xec, 0x56, 0x0d, 0x85, 0xb6, 0xe2, 0xaa, 0x95, 0x00, 0x89, 0x3f, 0x2a, 0x2b, 0xd0, 0xec,
	0xd2, 0x45, 0x5d, 0xf5, 0xc2, 0x99, 0x31, 0x64, 0xb4, 0xc9, 0xcc, 0xd4, 0xe3, 0x6c, 0x59, 0xb5,
	0x57, 0xbd, 0xed, 0x43, 0x54, 0xea, 0x53, 0xf4, 0xf1, 0x2a, 0x7b, 0x6c, 0x8f, 0x67, 0x12, 0x20,
	0xd2, 0xf6, 0x2a, 0xe3, 0x73, 0x7c, 0x3e, 0x7f, 0x3e, 0xe7, 0xf8, 0xb3, 0x03, 0xbd, 0x9b, 0x80,
	0x0f, 0xc6, 0xfd, 0x9e, 0x17, 0x8d, 0xb6, 0x7d, 0x12, 0xc7, 0x43, 0xfa, 0x71, 0xfb, 0x26, 0xfa,
	0x52, 0x7f, 0xb2, 0xd8, 0xdb, 0x8e, 0xfb, 0xe2, 0xa7, 0x17, 0xb3, 0x88, 0x47, 0xa8, 0xca, 0x62,
	0x2f, 0xee, 0x3b, 0x7b, 0xf7, 0x87, 0x85, 0x94, 0xff, 0x1a, 0xb1, 0xf7, 0x22, 0x34, 0xa6, 0x94,
	0x0d, 0x83, 0x84, 0xa7, 0xf1, 0xce, 0xce, 0xfd, 0x81, 0x5e, 0xc4, 0xa8, 0x88, 0xea, 0x0f, 0x23,
	0xef, 0xbd, 0x0a, 0xd9, 0x9b, 0x2d, 0x84, 0x33, 0x12, 0x26, 0xc4, 0xe3, 0x41, 0x14, 0xa6, 0x81,
	0xf8, 0x14, 0x5a, 0x87, 0x8c, 0x12, 0x4e, 0xdf, 0x92, 0xe1, 0x90, 0x72, 0x97, 0xfe, 0x32, 0xa6,
	0x09, 0x47, 0x08, 0xe6, 0x43, 0x32, 0xa2, 0x9d, 0xd2, 0x56, 0xa9, 0xbb, 0xe8, 0xca, 0x6f, 0xb4,
	0x09, 0x10, 0x93, 0x24, 0x89, 0x07, 0x8c, 0x24, 0xb4, 0x53, 0x96, 0x1e, 0xcb, 0x82, 0x5f, 0x40,
	0xeb, 0x32, 0x14, 0x9c, 0x1e, 0x84, 0xc2, 0x5f, 0xc1, 0x6a, 0x7e, 0x6a, 0x12, 0x47, 0x61, 0x42,
	0x51, 0x07, 0x16, 0x46, 0x34, 0x49, 0xc8, 0x8d, 0x9e, 0xae, 0x87, 0xf8, 0x00, 0xd0, 0xbe, 0xef,
	0x5f, 0xb0, 0xc8, 0x1f, 0x7b, 0x94, 0xdd, 0x47, 0xb3, 0x03, 0x0b, 0xc4, 0xf7, 0x19, 0x4d, 0x12,
	0xc5, 0x51, 0x0f, 0x31, 0x81, 0xc7, 0xc7, 0x94, 0x1f, 0x90, 0x21, 0x09, 0x3d, 0xfa, 0x09, 0x3b,
	0xb5, 0x97, 0xa8, 0xe4, 0x97, 0xf8, 0x1e, 0x56, 0x5f, 0xd3, 0xd0, 0x3f, 0x62, 0xd1, 0xe8, 0x55,
	0x10, 0x66, 0x44, 0x97, 0xa0, 0xcc, 0x23, 0xb5, 0x46, 0x99, 0x47, 0xa8, 0x0d, 0x35, 0x32, 0x8a,
	0xc6, 0x21, 0x97, 0xe8, 0x0d, 0x57, 0x8d, 0xf0, 0x6f, 0x50, 0x17, 0xf1, 0x16, 0xb9, 0x6b, 0x16,
	0x8d, 0x34, 0x39, 0xf1, 0xad, 0xa0, 0xca, 0x53, 0xa0, 0x2a, 0x36, 0x94, 0xd8, 0x44, 0x9a, 0xdd,
	0x98, 0xf0, 0x41, 0x67, 0x3e, 0xdd, 0x44, 0x66, 0x41, 0x2b, 0x50, 0xe1, 0x41, 0xdc, 0xa9, 0x6e,
	0x95, 0xba, 0xf3, 0xae, 0xf8, 0xc4, 0xaf, 0x60, 0xfd, 0x98, 0xf2, 0x74, 0xca, 0x7e, 0xba, 0xa1,
	0x4f, 0xe9, 0x87, 0x55, 0x40, 0xc7, 0x94, 0x5f, 0x50, 0xca, 0x4e, 0xc3, 0xeb, 0x48, 0x21, 0x61,
	0x07, 0x3a, 0xa2, 0x08, 0xa2, 0xf8, 0xde, 0x80, 0x04, 0xa1, 0xed, 0xdb, 0x85, 0x25, 0x51, 0x64,
	0x9a, 0xe5, 0x6d, 0x0b, 0xea, 0xd7, 0xe3, 0xe1, 0x50, 0xb1, 0x51, 0xcb, 0xdb, 0x26, 0xbc, 0x0d,
	0xad, 0x5c, 0x63, 0x3c, 0xd8, 0x49, 0x47, 0x92, 0x96, 0xe9, 0x82, 0x87, 0xe6, 0x17, 0x4a, 0x55,
	0x31, 0xa5, 0xda, 0x81, 0xb5, 0x42, 0xa9, 0x1f, 0x5c, 0xba, 0x0b, 0x8d, 0xb4, 0xba, 0x33, 0x90,
	0x6c, 0xe5, 0x72, 0xa7, 0x02, 0xb6, 0xe1, 0x91, 0xd0, 0x8a, 0xb3, 0x20, 0xe1, 0x32, 0xa2, 0xbe,
	0xdb, 0xea, 0x29, 0x1d, 0x89, 0xfb, 0xbd, 0x0b, 0x25, 0x23, 0xae, 0x99, 0x84, 0xff, 0x2a, 0xc1,
	0x93, 0x29, 0xe9, 0x56, 0x70, 0xcf, 0xa1, 0xc9, 0x49, 0x30, 0x94, 0xde, 0x13, 0x92, 0x0c, 0x24,
	0x66, 0xc3, 0xcd, 0x1b, 0x45, 0x0d, 0xa4, 0xd4, 0x9c, 0xd0, 0xe0, 0x66, 0x90, 0x66, 0x61, 0xde,
	0xb5, 0x4d, 0x68, 0x03, 0x16, 0x63, 0x55, 0x00, 0x71, 0x22, 0x2a, 0xdd, 0x45, 0x37, 0x33, 0x08,
	0x2f, 0x0f, 0x46, 0x34, 0xe1, 0x64, 0x14, 0xcb, 0x3e, 0xac, 0xb8, 0x99, 0x01, 0xbf, 0x80, 0x65,
	0x53, 0x73, 0x45, 0xab, 0x0d, 0xb5, 0x84, 0x13, 0x3e, 0xd6, 0xf5, 0x56, 0x23, 0xbc, 0x27, 0xcf,
	0xef, 0x8f, 0x94, 0x25, 0x41, 0x14, 0xea, 0x0e, 0xc1, 0xd0, 0x90, 0x4a, 0xa6, 0xcc, 0x2a, 0x24,
	0x67, 0xc3, 0xbf, 0xcb, 0x92, 0x9b, 0x40, 0xb5, 0xcc, 0x06, 0x2c, 0x52, 0xc6, 0x22, 0x76, 0x18,
	0xf9, 0x69, 0xfe, 0x9b, 0x6e, 0x66, 0x98, 0xc0, 0x2d, 0x4f, 0xe2, 0x8a, 0xfc, 0x25, 0x94, 0x7d,
	0xa0, 0x4c, 0x4f, 0x4a, 0xd5, 0x20, 0x6f, 0xc4, 0x2f, 0x61, 0xe9, 0x98, 0xf2, 0xcb, 0x37, 0x57,
	0xe7, 0x9a, 0xb3, 0xa5, 0x1f, 0xa5, 0xbc, 0x7e, 0xfc, 0x59, 0x82, 0x65, 0x33, 0x79, 0x26, 0x9e,
	0xff, 0x87, 0xea, 0x98, 0xdf, 0x46, 0x42, 0xec, 0x2a, 0xdd, 0xfa, 0x6e, 0xbd, 0x27, 0x2f, 0x9f,
	0x9e, 0x44, 0x48, 0x3d, 0x68, 0x0f, 0x1a, 0xaa, 0x5a, 0xc4, 0xd7, 0x15, 0x12, 0x9d, 0x23, 0x6e,
	0x85, 0xb8, 0xdf, 0x3b, 0xc8, 0x7c, 0x6e, 0x6e, 0x22, 0x66, 0x30, 0x2f, 0x70, 0xac, 0x23, 0x50,
	0xca, 0x49, 0xcc, 0x73, 0x68, 0xc6, 0xe3, 0xfe, 0x30, 0xf0, 0x7e, 0xa0, 0x1f, 0x65, 0xff, 0xa4,
	0x62, 0x96, 0x37, 0x0a, 0xed, 0xe0, 0xb7, 0x81, 0xaf, 0xe4, 0x49, 0x7e, 0x8b, 0x0c, 0xf0, 0xdb,
	0xd3, 0xd0, 0xa7, 0xb7, 0xb2, 0x23, 0x9a, 0xae, 0x1e, 0xe2, 0x9f, 0x60, 0x45, 0x37, 0xac, 0x51,
	0x9f, 0x97, 0xb0, 0x92, 0x70, 0xc2, 0xb8, 0xe9, 0x49, 0x2a, 0x12, 0x57, 0xe9, 0x36, 0xdc, 0x09,
	0x3b, 0x72, 0xe0, 0xd1, 0x88, 0xdc, 0x1e, 0x9a, 0x03, 0x5b, 0x75, 0xcd, 0x18, 0x5f, 0xa5, 0x17,
	0x80, 0xc2, 0x9e, 0x29, 0xbd, 0x9f, 0x43, 0x4d, 0xa6, 0x44, 0xe7, 0xb7, 0x99, 0xcb, 0x9a, 0xab,
	0x9c, 0xf8, 0x0b, 0x58, 0xd3, 0xc8, 0x07, 0x72, 0xd7, 0x96, 0x70, 0x0e, 0xb2, 0x93, 0x25, 0xbf,
	0xf1, 0x3b, 0x68, 0x17, 0x27, 0xcf, 0xc4, 0xe5, 0x33, 0xa8, 0xca, 0xe5, 0xe4, 0xbe, 0x26, 0xa8,
	0xa4, 0x3e, 0xbc, 0x23, 0x45, 0x5c, 0x83, 0xcb, 0xf3, 0xa9, 0xb9, 0xb4, 0xa1, 0x36, 0x48, 0xcf,
	0x70, 0x49, 0x9e, 0x61, 0x35, 0xc2, 0x3f, 0x67, 0x92, 0x9c, 0x85, 0xfc, 0x77, 0x8c, 0xce, 0xa1,
	0x2d, 0x54, 0xef, 0x4d, 0xf6, 0xf6, 0xd0, 0x84, 0xbe, 0x85, 0xba, 0xf5, 0x22, 0x31, 0x8a, 0xa6,
	0x40, 0xec, 0x00, 0x7b, 0x1e, 0xde, 0x83, 0xf5, 0x09, 0xc0, 0x59, 0xe8, 0xee, 0xfe, 0x51, 0x05,
	0x70, 0x63, 0xef, 0x35, 0x65, 0x1f, 0x02, 0x8f, 0xa2, 0x23, 0x68, 0xba, 0xb1, 0x97, 0x29, 0x03,
	0xea, 0xa8, 0xc3, 0x33, 0xa1, 0x32, 0xce, 0x93, 0x29, 0x9e, 0x74, 0x49, 0x3c, 0x97, 0xe1, 0xa8,
	0x4b, 0xc5, 0xc6, 0xc9, 0xbf, 0x36, 0x6c, 0x9c, 0xc2, 0x0d, 0x84, 0xe7, 0xd0, 0x3b, 0x58, 0x55,
	0x38, 0x39, 0xb9, 0x46, 0xcf, 0xac, 0xa0, 0x69, 0xf7, 0xa6, 0xb3, 0x75, 0xf7, 0x04, 0x03, 0xfe,
	0x9d, 0xdc, 0xba, 0xd2, 0x16, 0xb4, 0x96, 0x45, 0x58, 0xc2, 0xe4, 0xb4, 0x8b, 0x66, 0x13, 0x7e,
	0x08, 0x0d, 0x8b, 0x5b, 0x82, 0xd6, 0x0b, 0x4b, 0xea, 0xb3, 0xea, 0x74, 0x26, 0x1d, 0x06, 0xc4,
	0x85, 0xc7, 0x16, 0x48, 0xda, 0xfb, 0x68, 0xa3, 0x10, 0x90, 0x3b, 0x3f, 0xce, 0xff, 0xee, 0xf0,
	0x1a, 0xcc, 0x2b, 0x68, 0xe5, 0x31, 0xd3, 0x2b, 0x69, 0x73, 0x32, 0xce, 0x3e, 0x0b, 0xce, 0xb3,
	0x3b, 0xfd, 0x06, 0xf9, 0x12, 0x90, 0x6c, 0x96, 0x5c, 0xa7, 0x21, 0x4d, 0x68, 0x7a, 0x4b, 0x3b,
	0x9b, 0x77, 0xb9, 0x35, 0xec, 0xee, 0x3f, 0x15, 0x68, 0xec, 0xfb, 0xa3, 0x20, 0xd4, 0x6d, 0x98,
	0x56, 0x46, 0x5d, 0x82, 0xa6, 0x32, 0xf9, 0x87, 0x90, 0xa9, 0x4c, 0xe1, 0xae, 0xc4, 0x73, 0xe8,
	0x1b, 0x58, 0x50, 0x34, 0x11, 0xb2, 0x16, 0xd7, 0x81, 0xad, 0x9c, 0xcd, 0x44, 0x9d, 0xc2, 0x52,
	0x9a, 0x36, 0xfd, 0xc6, 0x40, 0x56, 0x6b, 0x16, 0xde, 0x6c, 0x8e, 0x33, 0xcd, 0x65, 0xa0, 0xce,
	0x61, 0x45, 0x11, 0x30, 0x6f, 0x21, 0xf4, 0xd4, 0x5a, 0xb5, 0xf8, 0x18, 0x76, 0x36, 0xa6, 0x3b,
	0x0b, 0xdc, 0xac, 0x57, 0x9d, 0xe1, 0x36, 0xf9, 0x17, 0xc0, 0x70, 0x9b, 0xf2, 0x08, 0xc4, 0x73,
	0xe8, 0x0c, 0x96, 0xdd, 0xd8, 0xb3, 0xff, 0x6b, 0x20, 0x1d, 0x30, 0xe5, 0xbf, 0x8a, 0xf3, 0x74,
	0xaa, 0x4f, 0xa3, 0x1d, 0xd4, 0xfe, 0x2e, 0x57, 0x4e, 0xce, 0xde, 0xf6, 0x6b, 0xf2, 0x15, 0xf0,
	0xf5, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xec, 0x11, 0xa3, 0x50, 0x19, 0x0e, 0x00, 0x00,
}
