// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScEngine is an autogenerated mock type for the ScEngine type
type ScEngine struct {
	mock.Mock
}

// Execute provides a mock function with given fields: function, args
func (_m *ScEngine) Execute(function string, args string) string {
	ret := _m.Called(function, args)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(function, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ImportLocalStorage provides a mock function with given fields: storage
func (_m *ScEngine) ImportLocalStorage(storage map[string]string) {
	_m.Called(storage)
}

// ImportSourceCode provides a mock function with given fields: source
func (_m *ScEngine) ImportSourceCode(source string) {
	_m.Called(source)
}
